table amazon_order_items
	lineageTag: 0cacaa14-d127-4a46-89d2-ae1948bf73bd

	measure 'Measure 2' =
			
			SWITCH(
			    TRUE(),
			    amazon_order_items[item_price_amount], amazon_order_items[item_price_amount],
			    ISBLANK(item_price_amount) && RELATED(amazon_orders[is_replacement]) = FALSE, "Missing data",
			    "IDK this data"
			    )
		lineageTag: e1397b91-f10d-4ee2-a94d-789198a19ea2

	column quantity_shipped
		dataType: int64
		formatString: 0
		lineageTag: de178791-dae1-4911-9828-e1c2039d8cd0
		summarizeBy: sum
		sourceColumn: quantity_shipped

		annotation SummarizationSetBy = Automatic

	column asin
		dataType: string
		lineageTag: 717b8b49-55ac-4c4a-9dc4-fc5b44909fd1
		summarizeBy: none
		sourceColumn: asin

		annotation SummarizationSetBy = Automatic

	column seller_sku
		dataType: string
		lineageTag: ef7009ea-ebf9-477f-b8fd-032f84f4dc35
		summarizeBy: none
		sourceColumn: seller_sku

		annotation SummarizationSetBy = Automatic

	column is_gift
		dataType: string
		lineageTag: cebb7847-95a7-4b87-a88a-4062e1efe5e1
		summarizeBy: none
		sourceColumn: is_gift

		annotation SummarizationSetBy = Automatic

	column is_transparency
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 78cb2e4a-7ee9-41ed-8858-7107dc0f7947
		summarizeBy: none
		sourceColumn: is_transparency

		annotation SummarizationSetBy = Automatic

	column quantity_ordered
		dataType: int64
		formatString: 0
		lineageTag: 1c6fc1a8-e94c-4795-adea-d26c580589b6
		summarizeBy: sum
		sourceColumn: quantity_ordered

		annotation SummarizationSetBy = Automatic

	column promotion_ids
		dataType: string
		lineageTag: 8bf3d3ce-ae3a-4471-a161-1fc7bfe571bb
		summarizeBy: none
		sourceColumn: promotion_ids

		annotation SummarizationSetBy = Automatic

	column order_item_id
		dataType: int64
		formatString: 0
		lineageTag: 141abb77-822a-4ef5-9d24-f97e71ee6324
		summarizeBy: sum
		sourceColumn: order_item_id

		annotation SummarizationSetBy = Automatic

	column product_info_number_of_items
		dataType: int64
		formatString: 0
		lineageTag: a82b79bb-1f11-4581-baf1-e6687d7cce74
		summarizeBy: sum
		sourceColumn: product_info_number_of_items

		annotation SummarizationSetBy = Automatic

	column item_tax_currency_code
		dataType: string
		lineageTag: 706ace01-2ff3-43a1-926b-10bbecc656af
		summarizeBy: none
		sourceColumn: item_tax_currency_code

		annotation SummarizationSetBy = Automatic

	column item_tax_amount
		dataType: double
		lineageTag: d9795e59-1497-47d9-9cb9-3b24a43bd027
		summarizeBy: none
		sourceColumn: item_tax_amount

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column item_price_currency_code
		dataType: string
		lineageTag: 8dcc4713-e216-4abb-9594-8f799e377ffa
		summarizeBy: none
		sourceColumn: item_price_currency_code

		annotation SummarizationSetBy = Automatic

	column item_price_amount
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: bd91cfd4-f516-4de7-a753-cb7860d625e8
		summarizeBy: sum
		sourceColumn: item_price_amount

		annotation SummarizationSetBy = User

	column shipping_tax_amount
		dataType: double
		lineageTag: 944c3639-5095-4346-9321-56406b009880
		summarizeBy: sum
		sourceColumn: shipping_tax_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column shipping_price_amount
		dataType: double
		lineageTag: bf4224fa-5dce-4f33-aa12-054fea677c79
		summarizeBy: sum
		sourceColumn: shipping_price_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column shipping_discount_amount
		dataType: double
		lineageTag: b9ff608d-47f9-4594-87cc-19f1705520a5
		summarizeBy: sum
		sourceColumn: shipping_discount_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column shipping_discount_tax_amount
		dataType: double
		lineageTag: dbbf990a-afe7-482c-952c-50e20812906c
		summarizeBy: sum
		sourceColumn: shipping_discount_tax_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column promotion_discount_tax_amount
		dataType: double
		lineageTag: 0fc8c2ab-291e-4b70-bc55-2f5f025108fc
		summarizeBy: sum
		sourceColumn: promotion_discount_tax_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column promotion_discount_amount
		dataType: double
		lineageTag: 7b262dc3-0bc5-44e6-a849-f48c7e07d470
		summarizeBy: sum
		sourceColumn: promotion_discount_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column amazon_order_id
		dataType: string
		lineageTag: 501ab23e-9820-4138-bd37-0bca41b4ea70
		summarizeBy: none
		sourceColumn: amazon_order_id

		annotation SummarizationSetBy = Automatic

	column buyer_info_gift_wrap_price_amount
		dataType: double
		lineageTag: 8e885f31-4a91-4b9c-9491-b45c8f81f2ea
		summarizeBy: sum
		sourceColumn: buyer_info_gift_wrap_price_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column buyer_info_gift_wrap_tax_amount
		dataType: double
		lineageTag: 7932ee68-b13a-4b42-9712-928824475737
		summarizeBy: sum
		sourceColumn: buyer_info_gift_wrap_tax_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column marketplace
		dataType: string
		lineageTag: aafa52ea-3b14-473f-9e4b-3e672ae55073
		summarizeBy: none
		sourceColumn: marketplace

		annotation SummarizationSetBy = Automatic

	column 'Coupon Fee'
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: f42dcb6b-6b7f-4a0b-9485-8c32996c6f8c
		summarizeBy: sum
		sourceColumn: Coupon Fee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Vine
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 92f78807-259e-4302-9574-a69b9150ca5e
		summarizeBy: none
		sourceColumn: Vine

		annotation SummarizationSetBy = Automatic

	partition amazon_order_items = m
		mode: import
		source = ```
				let
				    Source = Value.NativeQuery(PostgreSQL.Database("edgepify.app", "ecommerce", [HierarchicalNavigation=true]), "SELECT#(lf)    t1.amazon_order_id,#(lf)    t1.order_item_id,#(lf)    t1.asin,#(lf)    t1.seller_sku,#(lf)    t1.is_gift,#(lf)    t1.is_transparency,#(lf)    t1.quantity_ordered,#(lf)    t1.quantity_shipped,#(lf)    t1.promotion_ids,#(lf)    t1.product_info_number_of_items,#(lf)    CASE -- Gets currency. If order_status = pending -> null.#(lf)    WHEN t2.purchase_date >= CURRENT_DATE - INTERVAL '7 days'#(lf)            AND (t1.item_price_currency_code IS NULL OR t1.item_price_currency_code = 'nan')#(lf)            AND t2.is_replacement_order = FALSE#(lf)        THEN t3.product_competitive_pricing_competitive_prices->0->'Price'->'ListingPrice'->>'CurrencyCode'#(lf)        ELSE t1.item_price_currency_code#(lf)    END AS ""item_price_currency_code"",#(lf)    CASE -- Gets Prime Exclusive Price if null#(lf)    WHEN t2.purchase_date >= CURRENT_DATE - INTERVAL '7 days'#(lf)            AND t1.item_price_amount IS NULL#(lf)            AND t2.is_replacement_order = FALSE#(lf)        THEN (t3.product_competitive_pricing_competitive_prices->0->'Price'->'ListingPrice'->'Amount')::FLOAT * t1.quantity_ordered#(lf)        ELSE t1.item_price_amount#(lf)    END AS ""item_price_amount"",#(lf)    t1.item_tax_currency_code,#(lf)    t1.item_tax_amount,#(lf)    t1.shipping_price_amount,#(lf)    t1.shipping_tax_amount,#(lf)    t1.shipping_discount_amount,#(lf)    t1.shipping_discount_tax_amount,#(lf)    t1.promotion_discount_amount,#(lf)    t1.promotion_discount_tax_amount,#(lf)    t1.buyer_info_gift_wrap_price_amount,#(lf)    t1.buyer_info_gift_wrap_tax_amount,#(lf)    t1.marketplace,#(lf)    CASE -- Determines if Vine order#(lf)    WHEN t2.order_status NOT IN ('Pending', 'Canceled')#(lf)            AND t1.item_price_amount IS NULL#(lf)            AND t2.is_replacement_order = FALSE#(lf)        THEN TRUE#(lf)        ELSE NULL#(lf)    END AS ""Vine""#(lf)FROM orders.amazon_order_items t1#(lf)LEFT JOIN orders.amazon_orders t2 ON t1.amazon_order_id = t2.amazon_order_id#(lf)LEFT JOIN (#(lf)            select DISTINCT ON (asin, marketplace)#(lf)            asin, marketplace, product_competitive_pricing_competitive_prices#(lf)            from product_pricing.competitive_pricing#(lf)            where customer_type = 'Business' and product_competitive_pricing_competitive_prices != '[]'#(lf)            order by asin, marketplace, date desc#(lf)            )#(lf)            AS t3 ON t1.asin = t3.asin AND t1.marketplace = t3.marketplace#(lf)ORDER BY purchase_date ASC", null, [EnableFolding=true]),
				    #"Added Conditional Column" = Table.AddColumn(Source, "Coupon Fee", each 
				    if [promotion_ids] <> null and Text.Contains([promotion_ids], "Coupon") and [marketplace] = "US" then 0.6
				    else if [promotion_ids] <> null and Text.Contains([promotion_ids], "Coupon") and [marketplace] = "CA" then 0.6
				    else if [promotion_ids] <> null and Text.Contains([promotion_ids], "Coupon") and [marketplace] = "UK" then 0.45
				    else 0),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Conditional Column",{{"Coupon Fee", type number}})
				in
				    #"Changed Type"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

