table 'COGS (WW)'
	lineageTag: c9acc4dc-d449-49f8-895d-8527fc4d9f7b

	column 'Parent Product'
		dataType: string
		lineageTag: 1868ba64-aaaa-4ddd-8aef-ec76b091162a
		summarizeBy: none
		sourceColumn: Parent Product

		annotation SummarizationSetBy = Automatic

	column 'Product Code'
		dataType: string
		lineageTag: 1b2cfce7-137e-4511-a16b-2256c2d5b443
		summarizeBy: none
		sourceColumn: Product Code

		annotation SummarizationSetBy = Automatic

	column SKU
		dataType: string
		lineageTag: f61e8cce-ca82-4378-9dd3-5cfe4aa6edab
		summarizeBy: none
		sourceColumn: SKU

		annotation SummarizationSetBy = Automatic

	column ASIN
		dataType: string
		lineageTag: c1da061c-c10e-42ef-a2ed-3b9fa39f5682
		summarizeBy: none
		sourceColumn: ASIN

		annotation SummarizationSetBy = Automatic

	column Marketplace
		dataType: string
		lineageTag: af312589-e675-4ac0-8b37-a126650b7a7f
		summarizeBy: none
		sourceColumn: Marketplace

		annotation SummarizationSetBy = Automatic

	column COGS
		dataType: decimal
		lineageTag: 8c1db475-2321-4603-89f5-c20da48c26d3
		summarizeBy: none
		sourceColumn: COGS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'FBA Fee'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 2b82c0e5-4cb2-4362-8217-183834eb003e
		summarizeBy: sum
		sourceColumn: FBA Fee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Storage
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: b98bdf2d-6898-4743-a143-5985e9ff8f26
		summarizeBy: sum
		sourceColumn: Storage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Returns
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: d94ada35-9b2a-4eb6-a8ed-bb2b3b80e2e9
		summarizeBy: sum
		sourceColumn: Returns

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Currency
		dataType: string
		lineageTag: c93cb81a-bb92-4e80-a20c-db623da045a6
		summarizeBy: none
		sourceColumn: Currency

		annotation SummarizationSetBy = Automatic

	column tenant_id
		dataType: string
		lineageTag: 88e5919b-8305-4236-9261-9c9c77e9ad7d
		summarizeBy: none
		sourceColumn: tenant_id

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0ed41201-3cc5-430e-bc6d-e1e8ff2b8a68
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'COGS (WW)' = m
		mode: import
		source =
				let
				    Source = Table.Combine({#"BB COGS (WW)", #"RY COGS (WW)"}),
				    #"Added Custom" = Table.AddColumn(Source, "Date", each List.Dates( [Date Start], Duration.Days( [Date End] - [Date Start] ) + 1, #duration(1, 0, 0, 0) ), type {date} ),
				    #"Expanded Date" = Table.ExpandListColumn(#"Added Custom", "Date"),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expanded Date",{"Date", "Date Start", "Date End", "Parent Product", "Product Code", "SKU", "ASIN", "Marketplace", "Currency", "COGS", "FBA Fee", "Storage", "Returns", "tenant_id"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"Date Start", "Date End"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

