table 'Dim Product Codes'
	lineageTag: dc0f50d9-f2a0-4c7e-81dc-8228fed075dc

	column sku
		dataType: string
		lineageTag: 1003c963-00e6-4238-8033-bf97218ea716
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column asin
		dataType: string
		lineageTag: fcb4dcb4-1613-422d-8e39-2a61ddc9d52e
		summarizeBy: none
		sourceColumn: asin

		annotation SummarizationSetBy = Automatic

	column product_type
		dataType: string
		lineageTag: 8826df46-2786-4dad-ad0c-16c5ee1ff72c
		summarizeBy: none
		sourceColumn: product_type

		annotation SummarizationSetBy = Automatic

	column tenant_id
		dataType: int64
		formatString: 0
		lineageTag: 42c48ccb-d3d6-4174-b620-c28e3a3b19e3
		summarizeBy: sum
		sourceColumn: tenant_id

		annotation SummarizationSetBy = Automatic

	column parent_code
		dataType: string
		lineageTag: 35232aef-f492-4249-b0c5-d0e3da2bbb62
		summarizeBy: none
		sourceColumn: parent_code

		annotation SummarizationSetBy = Automatic

	column shaker_code
		dataType: string
		lineageTag: d4871ea6-1629-4b42-85e9-6a70327fbbe8
		summarizeBy: none
		sourceColumn: shaker_code

		annotation SummarizationSetBy = Automatic

	column portfolio_code
		dataType: string
		lineageTag: 6d38ab06-95fa-4d71-a3c5-1bcafa43f388
		summarizeBy: none
		sourceColumn: portfolio_code

		annotation SummarizationSetBy = Automatic

	column product_code
		dataType: string
		lineageTag: fd44e847-db49-4d88-9e86-6c79d128f3f1
		summarizeBy: none
		sourceColumn: product_code

		annotation SummarizationSetBy = Automatic

	partition 'Dim Product Codes' = m
		mode: import
		source =
				let
				    Source = Table.Combine({#"Dim BB Product Codes", #"Dim RY Product Codes"}),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"parent_shaker_code", "portfolio_code"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

