table 'Dim Marketplace'
	lineageTag: 0502c810-5c63-4dff-8523-af2742970071

	column marketplace
		dataType: string
		lineageTag: 167da889-fe85-4aa1-8e68-a55d66233700
		summarizeBy: none
		sourceColumn: marketplace

		annotation SummarizationSetBy = Automatic

	column marketplace_id
		dataType: string
		lineageTag: b21c5f94-c845-4fec-a230-53110f181a03
		summarizeBy: none
		sourceColumn: marketplace_id

		annotation SummarizationSetBy = Automatic

	column sales_channel
		dataType: string
		lineageTag: 5fe22727-a79d-4b3c-9e40-0c5f6a826df6
		summarizeBy: none
		sourceColumn: sales_channel

		annotation SummarizationSetBy = Automatic

	partition 'Dim Marketplace' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WcnZU0lFyNHINDTQMD3F3DnFyNwIJ5CZW5efpJScqxepEK4V6g4QM3SyM3S2cjRyD/M0DkNTk65VmQ5QFg0RDwgJcvD29IwxcXIOQVeUqxcYCAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t, Column3 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "marketplace"}, {"Column2", "marketplace_id"}, {"Column3", "sales_channel"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

