table 'Dim Product Codes'
	lineageTag: 832e376b-a445-4b36-a1d4-9f1295586bc1

	column asin
		dataType: string
		lineageTag: cb9a7038-9c7f-4360-8af4-1f2d3715f400
		summarizeBy: none
		sourceColumn: asin

		annotation SummarizationSetBy = Automatic

	column product_type
		dataType: string
		lineageTag: 10168281-cd2b-4825-853e-485519691bea
		summarizeBy: none
		sourceColumn: product_type

		annotation SummarizationSetBy = Automatic

	column sku
		dataType: string
		lineageTag: 738cdcb5-d6da-48b5-9be7-0e637b0b5ec6
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column portfolio_code
		dataType: string
		lineageTag: 3b7eca4e-b82a-4fdd-8e7e-4bdf15bb881f
		summarizeBy: none
		sourceColumn: portfolio_code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column parent_code
		dataType: string
		lineageTag: 2c197298-36ba-4738-afba-41b08318cbe4
		summarizeBy: none
		sourceColumn: parent_code

		annotation SummarizationSetBy = Automatic

	column shaker_code
		dataType: string
		lineageTag: e09af2d1-8893-4715-a18f-45e8400c2495
		summarizeBy: none
		sourceColumn: shaker_code

		annotation SummarizationSetBy = Automatic

	column product_code
		dataType: string
		lineageTag: 3e6f8263-c696-4334-aad9-b3a31237ef2d
		summarizeBy: none
		sourceColumn: product_code

		annotation SummarizationSetBy = Automatic

	column tenant_id
		dataType: int64
		formatString: 0
		lineageTag: 52495ee2-3366-4cd9-a110-dc4082f771d7
		summarizeBy: sum
		sourceColumn: tenant_id

		annotation SummarizationSetBy = Automatic

	partition 'Dim Product Codes' = m
		mode: import
		source =
				let
				    Source = Table.Combine({#"Dim BB Product Codes", #"Dim RY Product Codes"}),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"parent_shaker_code", "portfolio_code"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

