table 'Dim Parent Portfolio Code'
	lineageTag: 78e943f5-a7a7-43bb-ac77-25cad134b54c

	column portfolio_code
		dataType: string
		lineageTag: 3612caa3-d592-4a4a-a213-5fe297bab397
		summarizeBy: none
		sourceColumn: portfolio_code

		annotation SummarizationSetBy = Automatic

	column parent_code
		dataType: string
		lineageTag: 185e310b-42fb-4b3b-8488-23e46b083200
		summarizeBy: none
		sourceColumn: parent_code

		annotation SummarizationSetBy = Automatic

	column product_type
		dataType: string
		lineageTag: adf2b540-8851-47f9-b716-137ec7541d89
		summarizeBy: none
		sourceColumn: product_type

		annotation SummarizationSetBy = Automatic

	column tenant_id
		dataType: int64
		formatString: 0
		lineageTag: 3b2605b6-9f96-49c8-86b6-d4be980e23c7
		summarizeBy: none
		sourceColumn: tenant_id

		annotation SummarizationSetBy = Automatic

	partition 'Dim Parent Portfolio Code' = m
		mode: import
		source =
				let
				    Source = Table.Combine({#"Dim BB Product Codes", #"Dim RY Product Codes"}),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"parent_shaker_code", "portfolio_code"}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns",{"tenant_id", "product_type", "parent_code", "portfolio_code"}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Removed Other Columns",{"portfolio_code", "parent_code", "product_type", "tenant_id"}),
				    #"Removed Duplicates" = Table.Distinct(#"Reordered Columns", {"portfolio_code"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

