table DimFBAPlanningInventory
	lineageTag: ef9eb182-bde6-4197-a787-a89b83f77657

	column marketplace
		dataType: string
		lineageTag: 5565c497-6f40-4c10-b5b4-b043e72e36a0
		summarizeBy: none
		sourceColumn: marketplace

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column asin
		dataType: string
		lineageTag: 6611eb45-9497-4af6-bce1-87f85bb24f03
		summarizeBy: none
		sourceColumn: asin

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column available
		dataType: int64
		formatString: 0
		lineageTag: 215d6af0-df6d-4c64-85f7-ac55f450665a
		summarizeBy: sum
		sourceColumn: available

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column pending_removal_quantity
		dataType: int64
		formatString: 0
		lineageTag: caeadd66-24d9-428c-9804-d341974b91b8
		summarizeBy: sum
		sourceColumn: pending_removal_quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column inv_age_0_to_90_days
		dataType: int64
		formatString: 0
		lineageTag: f0b389ec-79dd-4ae8-afb7-16cf3ee20df5
		summarizeBy: sum
		sourceColumn: inv_age_0_to_90_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column inv_age_91_to_180_days
		dataType: int64
		formatString: 0
		lineageTag: 0d13a44b-28b1-43fc-bc76-b383645b6ac5
		summarizeBy: sum
		sourceColumn: inv_age_91_to_180_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column inv_age_181_to_270_days
		dataType: int64
		formatString: 0
		lineageTag: fd882e33-62f6-47c3-85b1-f5f18f0c8407
		summarizeBy: sum
		sourceColumn: inv_age_181_to_270_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column inv_age_271_to_365_days
		dataType: int64
		formatString: 0
		lineageTag: 35bc5813-87e1-4301-8980-5063e713e42c
		summarizeBy: sum
		sourceColumn: inv_age_271_to_365_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column inv_age_365_plus_days
		dataType: int64
		formatString: 0
		lineageTag: 61abc84b-31e2-496c-b422-71e1a8fe8613
		summarizeBy: sum
		sourceColumn: inv_age_365_plus_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column units_shipped_t_7
		dataType: double
		lineageTag: 60b52d8e-e445-49ca-a1eb-c85ed37893b1
		summarizeBy: sum
		sourceColumn: units_shipped_t_7

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column units_shipped_t_30
		dataType: double
		lineageTag: df078533-11a5-402e-9a5b-afaa6d83e585
		summarizeBy: sum
		sourceColumn: units_shipped_t_30

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column units_shipped_t_60
		dataType: double
		lineageTag: 9a4d2680-cab0-42e7-8dbd-1ab742208e1d
		summarizeBy: sum
		sourceColumn: units_shipped_t_60

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column units_shipped_t_90
		dataType: double
		lineageTag: e2c32902-73ba-46a5-8cbb-2dc6c2a24206
		summarizeBy: sum
		sourceColumn: units_shipped_t_90

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column alert
		dataType: string
		lineageTag: fabd487d-4e3b-4e95-b6d3-1f84f8c3325a
		summarizeBy: none
		sourceColumn: alert

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column your_price
		dataType: double
		lineageTag: 60632350-6eb3-413a-bdd2-37619acc6b51
		summarizeBy: sum
		sourceColumn: your_price

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_price
		dataType: double
		lineageTag: ed9c8304-258f-4436-9adb-dfe18755f155
		summarizeBy: sum
		sourceColumn: sales_price

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lowest_price_new_plus_shipping
		dataType: double
		lineageTag: 73cdee68-49a7-406e-8e24-f8d8885db2d4
		summarizeBy: sum
		sourceColumn: lowest_price_new_plus_shipping

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lowest_price_used
		dataType: double
		lineageTag: 9b5342c8-9db4-4d9f-b7a6-60b83aebb08a
		summarizeBy: sum
		sourceColumn: lowest_price_used

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column recommended_action
		dataType: string
		lineageTag: eb98fbbc-8844-49f9-9070-3fc59e0416cb
		summarizeBy: none
		sourceColumn: recommended_action

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column healthy_inventory_level
		dataType: double
		lineageTag: b1929108-9422-47a0-a206-74411dcac93c
		summarizeBy: sum
		sourceColumn: healthy_inventory_level

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column recommended_sales_price
		dataType: double
		lineageTag: 5613c53e-792d-4ca3-aeb8-b8c1148a092c
		summarizeBy: sum
		sourceColumn: recommended_sales_price

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column recommended_sale_duration_days
		dataType: double
		lineageTag: 01a6d632-16e5-4c79-b42b-4b4f3483ea0c
		summarizeBy: sum
		sourceColumn: recommended_sale_duration_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column recommended_removal_quantity
		dataType: double
		lineageTag: d5b1460c-22b1-4c27-93d7-310bb7afb7f0
		summarizeBy: sum
		sourceColumn: recommended_removal_quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column estimated_cost_savings_of_recommended_actions
		dataType: double
		lineageTag: 1f2966e5-7bbb-47ff-915f-b93cce57ee79
		summarizeBy: sum
		sourceColumn: estimated_cost_savings_of_recommended_actions

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sell_through
		dataType: double
		lineageTag: ab953018-a528-428d-9176-aa19d706968b
		summarizeBy: sum
		sourceColumn: sell_through

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column item_volume
		dataType: double
		lineageTag: 4e1a7af6-e9a1-4cdc-8ae3-27010925bf6f
		summarizeBy: sum
		sourceColumn: item_volume

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column storage_volume
		dataType: double
		lineageTag: 273b3606-39a4-454a-9f3e-b3bf92a7ffe7
		summarizeBy: sum
		sourceColumn: storage_volume

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_rank
		dataType: double
		lineageTag: 85fd0c1e-cc3b-49d9-b624-47bc6cfd738f
		summarizeBy: sum
		sourceColumn: sales_rank

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column days_of_supply
		dataType: int64
		formatString: 0
		lineageTag: dbb76785-6b09-4283-bcf9-291439bb316a
		summarizeBy: sum
		sourceColumn: days_of_supply

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column estimated_excess_quantity
		dataType: int64
		formatString: 0
		lineageTag: d8d0d515-d602-43c2-8b7c-f20606622841
		summarizeBy: sum
		sourceColumn: estimated_excess_quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column weeks_of_cover_t_30
		dataType: double
		lineageTag: 9d1cb22b-d4f0-4d09-a12c-59a72d38f957
		summarizeBy: sum
		sourceColumn: weeks_of_cover_t_30

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weeks_of_cover_t_90
		dataType: double
		lineageTag: e86a197d-dc90-4f22-aae3-aab4d79036ce
		summarizeBy: sum
		sourceColumn: weeks_of_cover_t_90

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column featuredoffer_price
		dataType: double
		lineageTag: 4162f9e3-6518-4a17-97f3-8a980ec863ae
		summarizeBy: sum
		sourceColumn: featuredoffer_price

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_shipped_last_7_days
		dataType: double
		lineageTag: 9f79f5d5-11b9-4993-ac3b-26f7cd83bbda
		summarizeBy: sum
		sourceColumn: sales_shipped_last_7_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_shipped_last_30_days
		dataType: double
		lineageTag: 88e3208e-e7c8-4a29-b138-1e3dc522b3ac
		summarizeBy: sum
		sourceColumn: sales_shipped_last_30_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_shipped_last_60_days
		dataType: double
		lineageTag: 703134d9-cedb-4e91-9465-6e705899eec3
		summarizeBy: sum
		sourceColumn: sales_shipped_last_60_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_shipped_last_90_days
		dataType: double
		lineageTag: 31b5a4e8-913f-4223-a61c-49fdbb2fdcea
		summarizeBy: sum
		sourceColumn: sales_shipped_last_90_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column inv_age_0_to_30_days
		dataType: int64
		formatString: 0
		lineageTag: 22dc0df3-2352-45da-9fe1-178a1d6978ee
		summarizeBy: sum
		sourceColumn: inv_age_0_to_30_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column inv_age_31_to_60_days
		dataType: int64
		formatString: 0
		lineageTag: 071ce4b4-fb62-43ef-8d7e-cb88d4584c82
		summarizeBy: sum
		sourceColumn: inv_age_31_to_60_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column inv_age_61_to_90_days
		dataType: int64
		formatString: 0
		lineageTag: a724b10a-c465-470f-a290-fe230e82757a
		summarizeBy: sum
		sourceColumn: inv_age_61_to_90_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column inv_age_181_to_330_days
		dataType: int64
		formatString: 0
		lineageTag: 16079c18-a79b-4e5a-9b6a-401d06c6d05a
		summarizeBy: sum
		sourceColumn: inv_age_181_to_330_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column inv_age_331_to_365_days
		dataType: int64
		formatString: 0
		lineageTag: ffc9c468-5395-4e5d-a5b0-70d0c7cf71a1
		summarizeBy: sum
		sourceColumn: inv_age_331_to_365_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column estimated_storage_cost_next_month
		dataType: double
		lineageTag: db3901aa-4ecb-48ea-8eee-48303e66c24d
		summarizeBy: sum
		sourceColumn: estimated_storage_cost_next_month

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column inbound_quantity
		dataType: int64
		formatString: 0
		lineageTag: fbb62954-e2a1-437f-ae5c-b2a08b5f875f
		summarizeBy: sum
		sourceColumn: inbound_quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column inbound_working
		dataType: int64
		formatString: 0
		lineageTag: 6f970385-21e8-43de-aa5d-56f0d3602f3f
		summarizeBy: sum
		sourceColumn: inbound_working

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column inbound_shipped
		dataType: int64
		formatString: 0
		lineageTag: 9583606b-a050-4646-84a0-28e3b8a4672c
		summarizeBy: sum
		sourceColumn: inbound_shipped

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column inbound_received
		dataType: int64
		formatString: 0
		lineageTag: 0348d2ce-0897-4577-913d-a930d46eb0bd
		summarizeBy: sum
		sourceColumn: inbound_received

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column no_sale_last_6_months
		dataType: double
		lineageTag: 29a1ea54-35b2-4491-86e5-035fa282a1ba
		summarizeBy: sum
		sourceColumn: no_sale_last_6_months

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column reserved_quantity
		dataType: int64
		formatString: 0
		lineageTag: 5d36a2cd-fe0c-458e-9fc7-43ad0eb23b8f
		summarizeBy: sum
		sourceColumn: reserved_quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column unfulfillable_quantity
		dataType: int64
		formatString: 0
		lineageTag: 251e9dbc-e5eb-4c5a-9bbc-7061375eec4c
		summarizeBy: sum
		sourceColumn: unfulfillable_quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column quantity_to_be_charged_ais_181_210_days
		dataType: double
		lineageTag: 340195c8-821d-4c98-8aed-e179d67056ca
		summarizeBy: sum
		sourceColumn: quantity_to_be_charged_ais_181_210_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column estimated_ais_181_210_days
		dataType: double
		lineageTag: df3a0410-6e78-4b31-be68-280cba6f4fc6
		summarizeBy: sum
		sourceColumn: estimated_ais_181_210_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column quantity_to_be_charged_ais_211_240_days
		dataType: double
		lineageTag: 78938a7c-dc6e-4588-b22a-d14928912e37
		summarizeBy: sum
		sourceColumn: quantity_to_be_charged_ais_211_240_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column estimated_ais_211_240_days
		dataType: double
		lineageTag: 846853cc-c903-4c0e-beb4-ab039128f879
		summarizeBy: sum
		sourceColumn: estimated_ais_211_240_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column quantity_to_be_charged_ais_241_270_days
		dataType: double
		lineageTag: aaa4ec4e-5487-402e-9c07-8def13d5bb7e
		summarizeBy: sum
		sourceColumn: quantity_to_be_charged_ais_241_270_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column estimated_ais_241_270_days
		dataType: double
		lineageTag: 27d70535-6590-4e5c-a838-1a6f86451ebd
		summarizeBy: sum
		sourceColumn: estimated_ais_241_270_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column quantity_to_be_charged_ais_271_300_days
		dataType: double
		lineageTag: e113a329-a271-423d-a004-c8d8dbaa9ae7
		summarizeBy: sum
		sourceColumn: quantity_to_be_charged_ais_271_300_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column estimated_ais_271_300_days
		dataType: double
		lineageTag: c028a645-fd9c-4134-9732-9a505916335b
		summarizeBy: sum
		sourceColumn: estimated_ais_271_300_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column quantity_to_be_charged_ais_301_330_days
		dataType: double
		lineageTag: ed4100fd-4975-42cc-a923-c9ea3554766d
		summarizeBy: sum
		sourceColumn: quantity_to_be_charged_ais_301_330_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column estimated_ais_301_330_days
		dataType: double
		lineageTag: 5a23c9d4-015d-47de-b12c-0135769d0cd6
		summarizeBy: sum
		sourceColumn: estimated_ais_301_330_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column quantity_to_be_charged_ais_331_365_days
		dataType: double
		lineageTag: 4791d09e-a8db-46e1-aa8d-722f146009f0
		summarizeBy: sum
		sourceColumn: quantity_to_be_charged_ais_331_365_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column estimated_ais_331_365_days
		dataType: double
		lineageTag: 7ef2c0b1-f897-4bda-905a-8c56e8b09bb7
		summarizeBy: sum
		sourceColumn: estimated_ais_331_365_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column quantity_to_be_charged_ais_365_plus_days
		dataType: double
		lineageTag: 803365b4-6263-4af6-8ede-2668f91acea2
		summarizeBy: sum
		sourceColumn: quantity_to_be_charged_ais_365_plus_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column estimated_ais_365_plus_days
		dataType: double
		lineageTag: 7a6018e6-68a3-4110-96be-67ff43ddaa17
		summarizeBy: sum
		sourceColumn: estimated_ais_365_plus_days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column qty_to_be_charged_ltsf_6_mo
		dataType: double
		lineageTag: 98457bcd-ae0f-435c-9250-e89d642478a5
		summarizeBy: sum
		sourceColumn: qty_to_be_charged_ltsf_6_mo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column projected_ltsf_6_mo
		dataType: double
		lineageTag: 87fd6f3c-6e3e-4658-9f1d-3616e836cdf0
		summarizeBy: sum
		sourceColumn: projected_ltsf_6_mo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column qty_to_be_charged_ltsf_12_mo
		dataType: double
		lineageTag: e34ac397-8203-4de0-9f0c-ebb8a8431ec8
		summarizeBy: sum
		sourceColumn: qty_to_be_charged_ltsf_12_mo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column estimated_ltsf_next_charge
		dataType: double
		lineageTag: 97a0e4ff-5d1a-47de-85a5-6ee5987903f5
		summarizeBy: sum
		sourceColumn: estimated_ltsf_next_charge

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tenant_id
		dataType: int64
		formatString: 0
		lineageTag: 73654a71-f2af-4f81-ae0b-a3122b537ad2
		summarizeBy: sum
		sourceColumn: tenant_id

		annotation SummarizationSetBy = Automatic

	partition DimFBAPlanningInventory = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("edgepify.app", "ecommerce", [HierarchicalNavigation=true]),
				    inventory = Source{[Schema="inventory"]}[Data],
				    fba_planning_inventory1 = inventory{[Name="fba_planning_inventory"]}[Data],
				    #"Sorted Rows" = Table.Sort(fba_planning_inventory1,{{"snapshot_date", Order.Descending}, {"asin", Order.Ascending}, {"marketplace", Order.Ascending}}),
				    #"Filtered Rows" = Table.SelectRows(#"Sorted Rows", each ([condition] = "New")),
				    #"Removed Duplicates" = Table.Distinct(#"Filtered Rows", {"marketplace", "asin"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Removed Duplicates",{"snapshot_date", "sku", "fnsku", "product_name", "condition", "currency", "storage_type", "product_group", "created_at", "updated_at", "volume_unit_measurement"})
				in
				    #"Removed Columns"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

