table h10_keyword_tracker
	lineageTag: cc1f61f6-ddec-4a51-a21b-3848c47173df

	refreshPolicy
		policyType: basic
		rollingWindowGranularity: year
		rollingWindowPeriods: 5
		incrementalGranularity: year
		incrementalPeriods: 2
		pollingExpression = let Maxupdated_at = List.Max(h10_keyword_tracker[updated_at]), accountForNull = if Maxupdated_at = null then #datetime(1901, 01, 01, 00, 00, 00) else Maxupdated_at in accountForNull
		sourceExpression =
			let
			    Source = GoogleBigQuery.Database(),
			    #"modern-sublime-383117" = Source{[Name="modern-sublime-383117"]}[Data],
			    rankings_Schema = #"modern-sublime-383117"{[Name="rankings",Kind="Schema"]}[Data],
			    h10_keyword_tracker = rankings_Schema{[Name="h10_keyword_tracker",Kind="Table"]}[Data],
			    #"Removed Columns" = Table.RemoveColumns(h10_keyword_tracker,{"_airbyte_raw_id", "_airbyte_extracted_at", "_airbyte_meta", "_airbyte_generation_id", "marketplace"}),
			    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns",306,null,Replacer.ReplaceValue,{"organic_rank"}),
			    #"Filtered Rows" = Table.SelectRows(#"Replaced Value", each [date_added] >= RangeStart and [date_added] <= RangeEnd)
			in
			    #"Filtered Rows"

	column asin
		dataType: string
		lineageTag: 37d76f77-288c-4680-b193-2ff0e3f81e05
		summarizeBy: none
		sourceColumn: asin

		annotation SummarizationSetBy = Automatic

	column keyword
		dataType: string
		lineageTag: bdf34e30-909a-4aa0-87fb-60cc38f468d2
		summarizeBy: none
		sourceColumn: keyword

		annotation SummarizationSetBy = Automatic

	column search_volume
		dataType: double
		formatString: #,0
		lineageTag: e565506b-8f89-4e0f-bb37-7c86953c8751
		summarizeBy: sum
		sourceColumn: search_volume

		annotation SummarizationSetBy = Automatic

	column organic_rank
		dataType: int64
		formatString: 0
		lineageTag: 8eb97df5-577b-49cb-8b81-6a58bb439e1b
		summarizeBy: sum
		sourceColumn: organic_rank

		annotation SummarizationSetBy = Automatic

	column sponsored_position
		dataType: double
		lineageTag: 4f80fbb9-200e-4a2e-9552-18f59709514d
		summarizeBy: sum
		sourceColumn: sponsored_position

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column date_added
		dataType: dateTime
		formatString: Long Date
		lineageTag: f2dc8464-31b0-42e8-9f39-d24752273af4
		summarizeBy: none
		sourceColumn: date_added

		annotation SummarizationSetBy = Automatic

	column marketplace_id
		dataType: string
		lineageTag: e88db623-bd6c-4354-b39a-daa06612f19a
		summarizeBy: none
		sourceColumn: marketplace_id

		annotation SummarizationSetBy = Automatic

	column title
		dataType: string
		lineageTag: 144c154e-a6a9-4329-9fdd-32ca88c4f2be
		summarizeBy: none
		sourceColumn: title

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: e97b3c30-f7b0-4729-8e64-bcedccaa5ab3
		summarizeBy: none
		sourceColumn: created_at

		variation Variation
			isDefault
			relationship: 0a2a5e64-788a-4b12-8b2e-54ef199f29ce
			defaultHierarchy: LocalDateTable_c1bf0275-2198-4958-87d8-d5f92107f400.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: a1fd1228-0159-4b22-bd7f-3a76d4630a14
		summarizeBy: none
		sourceColumn: updated_at

		variation Variation
			isDefault
			relationship: 75bf0272-a878-42f7-8a8a-073b1fc280e8
			defaultHierarchy: LocalDateTable_a8b55f7a-5589-4df7-9953-5272cdb67245.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition h10_keyword_tracker = m
		mode: import
		source =
				let
				    Source = GoogleBigQuery.Database(),
				    #"modern-sublime-383117" = Source{[Name="modern-sublime-383117"]}[Data],
				    rankings_Schema = #"modern-sublime-383117"{[Name="rankings",Kind="Schema"]}[Data],
				    h10_keyword_tracker = rankings_Schema{[Name="h10_keyword_tracker",Kind="Table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(h10_keyword_tracker,{"_airbyte_raw_id", "_airbyte_extracted_at", "_airbyte_meta", "_airbyte_generation_id", "marketplace"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns",306,null,Replacer.ReplaceValue,{"organic_rank"}),
				    #"Filtered Rows" = Table.SelectRows(#"Replaced Value", each [date_added] >= RangeStart and [date_added] <= RangeEnd)
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_IsMQueryFoldable = True

