table 'h10_keyword_tracker Search Volume'
	lineageTag: ff9dc987-a92c-4613-af13-53b363dece93

	measure 'Last Year search_volume' = CALCULATE(SUM('h10_keyword_tracker Search Volume'[search_volume]), SAMEPERIODLASTYEAR('Dim Date'[Date]))
		formatString: #,0
		lineageTag: 36aff85e-9b5c-4130-9bc6-34bfb87dfe94

	column date_added
		dataType: dateTime
		formatString: General Date
		lineageTag: 96409299-95c4-42a2-b5f0-ffa1b3530731
		summarizeBy: none
		sourceColumn: date_added

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column marketplace_id
		dataType: string
		lineageTag: 34b869fb-72cc-46a4-8705-4ab981665283
		summarizeBy: none
		sourceColumn: marketplace_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column keyword
		dataType: string
		lineageTag: 45a41043-759f-447d-b6d4-05fa814b2a77
		summarizeBy: none
		sourceColumn: keyword

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column search_volume
		dataType: double
		formatString: #,0
		lineageTag: b9442a77-c5f9-4614-a236-e71a00336565
		summarizeBy: sum
		sourceColumn: search_volume

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'h10_keyword_tracker Search Volume' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(PostgreSQL.Database("edgepify.app", "ecommerce", [HierarchicalNavigation=true]), "SELECT#(lf)    date_added::DATE,#(lf)    marketplace_id,#(lf)    keyword,#(lf)    MAX(search_volume) search_volume#(lf)FROM rankings.h10_keyword_tracker#(lf)GROUP BY date_added::DATE, marketplace_id, keyword", null, [EnableFolding=true])
				in
				    Source

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

