table 'Orders KPI Tracker'
	lineageTag: 6787abb5-57ce-4161-8e24-e7f4858dba6b

	column purchase_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d357186a-3f2a-4e4d-b506-df36b42d1940
		summarizeBy: none
		sourceColumn: purchase_date

		variation Variation
			isDefault
			relationship: 6e320681-c547-4822-8b1a-064f796ce3bf
			defaultHierarchy: LocalDateTable_c3997e70-f216-44f2-98a3-83bbdc591d5b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column marketplace
		dataType: string
		lineageTag: 44a393e9-9e0b-420a-a9a7-5d712b7526dd
		summarizeBy: none
		sourceColumn: marketplace

		annotation SummarizationSetBy = Automatic

	column order_status
		dataType: string
		lineageTag: b0c66287-399e-4416-92ea-dae064810211
		summarizeBy: none
		sourceColumn: order_status

		annotation SummarizationSetBy = Automatic

	column asin
		dataType: string
		lineageTag: ac28cf41-7ff8-4e98-8fa1-898bedc384c8
		summarizeBy: none
		sourceColumn: asin

		annotation SummarizationSetBy = Automatic

	column seller_sku
		dataType: string
		lineageTag: e8e9e82b-d579-435c-b7eb-92cb98a831a3
		summarizeBy: none
		sourceColumn: seller_sku

		annotation SummarizationSetBy = Automatic

	column product_code
		dataType: string
		lineageTag: 72328ae8-3295-410b-a4ec-54c1cad12665
		summarizeBy: none
		sourceColumn: product_code

		annotation SummarizationSetBy = Automatic

	column quantity_ordered
		dataType: int64
		formatString: 0
		lineageTag: 3b2a1ed3-beec-4aba-8344-c323a08263b9
		summarizeBy: sum
		sourceColumn: quantity_ordered

		annotation SummarizationSetBy = Automatic

	column net_item_price_per_unit
		dataType: double
		lineageTag: a649c376-6c3d-4cd0-92d3-5dbb2d5ab394
		summarizeBy: sum
		sourceColumn: net_item_price_per_unit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column item_price_amount
		dataType: double
		lineageTag: 3691c5f2-959f-40dc-932b-bba74726f6e7
		summarizeBy: sum
		sourceColumn: item_price_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column promotion_discount_amount
		dataType: double
		lineageTag: 06d90829-4258-4d54-8c3f-d85caa8f8f03
		summarizeBy: sum
		sourceColumn: promotion_discount_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column item_tax_amount
		dataType: double
		lineageTag: 5d232ddd-a91b-4e6a-a4fc-a36074e88bb1
		summarizeBy: sum
		sourceColumn: item_tax_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column net_item_price_amount
		dataType: double
		lineageTag: cefe36a5-89a7-45ce-ac63-7f4a9a471317
		summarizeBy: sum
		sourceColumn: net_item_price_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column coupon_fee
		dataType: double
		lineageTag: 68fd4be0-467d-4814-a3bb-430eda3db073
		summarizeBy: sum
		sourceColumn: coupon_fee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column item_price_currency_code
		dataType: string
		lineageTag: e7c1914b-3fe5-45c6-8a40-8a1be80a7b46
		summarizeBy: none
		sourceColumn: item_price_currency_code

		annotation SummarizationSetBy = Automatic

	column is_vine
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ea381bac-172c-4f12-9031-bea46b3cb9e7
		summarizeBy: none
		sourceColumn: is_vine

		annotation SummarizationSetBy = Automatic

	column is_replacement_order
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 79699883-a877-4b6e-a573-4d6ec461879e
		summarizeBy: none
		sourceColumn: is_replacement_order

		annotation SummarizationSetBy = Automatic

	column tenant_id
		dataType: int64
		formatString: 0
		lineageTag: bec8b985-ec30-4d30-831a-f46103e198c7
		summarizeBy: none
		sourceColumn: tenant_id

		annotation SummarizationSetBy = Automatic

	column COGS
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: bf7cc57d-b13c-446f-ad18-73b0d446dba2
		summarizeBy: sum
		sourceColumn: COGS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'FBA Fee'
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: b116c9b9-af19-489c-9df2-8b8f90856704
		summarizeBy: sum
		sourceColumn: FBA Fee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Storage
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: cef5e64e-b3ac-42f4-8b36-ca07477778f6
		summarizeBy: sum
		sourceColumn: Storage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column cost_of_goods_sold
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: e596cfcf-e0bd-425f-a690-17ef552b60d8
		summarizeBy: sum
		sourceColumn: cost_of_goods_sold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column fba_fee
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 95cb85af-22a7-4a28-ac1f-a4a57765ea75
		summarizeBy: sum
		sourceColumn: fba_fee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column storage_fee
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: fe473471-a08a-40e8-9abb-c527e4468df0
		summarizeBy: sum
		sourceColumn: storage_fee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition 'Orders KPI Tracker' = m
		mode: import
		source =
				let
				    Source = Table.NestedJoin(amazon_orders_summary_view, {"asin", "seller_sku", "marketplace", "purchase_date"}, #"COGS (WW)", {"ASIN", "SKU", "Marketplace", "Date"}, "COGS (WW)", JoinKind.LeftOuter),
				    #"Expanded COGS (WW)" = Table.ExpandTableColumn(Source, "COGS (WW)", {"COGS", "FBA Fee", "Storage"}, {"COGS", "FBA Fee", "Storage"}),
				    #"Added COGS" = Table.AddColumn(#"Expanded COGS (WW)", "cost_of_goods_sold", each [COGS] * [quantity_ordered]),
				    #"Added FBA Fee" = Table.AddColumn(#"Added COGS", "fba_fee", each [Storage] * [quantity_ordered]),
				    #"Added Storage Fee" = Table.AddColumn(#"Added FBA Fee", "storage_fee", each [Storage] * [quantity_ordered]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Storage Fee",{{"cost_of_goods_sold", Currency.Type}, {"fba_fee", Currency.Type}, {"storage_fee", Currency.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

