table 'SB campaign'
	lineageTag: d5896f4f-1ff7-4e02-8ea5-a51ec12e340b

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2b321f72-43dc-4279-a35b-8371bb06a286
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column marketplace
		dataType: string
		lineageTag: 4b2499cc-549a-4164-b84b-8d9d7750cbef
		summarizeBy: none
		sourceColumn: marketplace

		annotation SummarizationSetBy = Automatic

	column new_to_brand_sales_clicks
		dataType: double
		lineageTag: 2b6a08f1-330e-40f4-a1d4-b6b75e29e5a5
		summarizeBy: sum
		sourceColumn: new_to_brand_sales_clicks

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column viewability_rate
		dataType: double
		lineageTag: ad698da7-5979-46ce-a116-4a2c1e58d65a
		summarizeBy: sum
		sourceColumn: viewability_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column purchases_clicks
		dataType: int64
		formatString: 0
		lineageTag: 4391899a-ac37-4256-85af-e0853afbaa74
		summarizeBy: sum
		sourceColumn: purchases_clicks

		annotation SummarizationSetBy = Automatic

	column detail_page_views
		dataType: int64
		formatString: 0
		lineageTag: b1973b73-6c7b-4237-b0ba-a162e60f4b1f
		summarizeBy: sum
		sourceColumn: detail_page_views

		annotation SummarizationSetBy = Automatic

	column new_to_brand_sales_percentage
		dataType: double
		lineageTag: 0dcf1f02-01ba-4bae-8677-e212a4d9a4fe
		summarizeBy: sum
		sourceColumn: new_to_brand_sales_percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column units_sold
		dataType: int64
		formatString: 0
		lineageTag: 57dafe41-0aa6-4de0-8731-92e15805bcc3
		summarizeBy: sum
		sourceColumn: units_sold

		annotation SummarizationSetBy = Automatic

	column sales
		dataType: double
		lineageTag: 7aa36f85-ffeb-4c04-8439-62fa5316f9e4
		summarizeBy: sum
		sourceColumn: sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cost_type
		dataType: string
		lineageTag: 67634141-3322-408a-a48c-5cfcc6c111ca
		summarizeBy: none
		sourceColumn: cost_type

		annotation SummarizationSetBy = Automatic

	column campaign_status
		dataType: string
		lineageTag: f67ca480-e0e5-447d-b202-cbdbef14f67c
		summarizeBy: none
		sourceColumn: campaign_status

		annotation SummarizationSetBy = Automatic

	column view_click_through_rate
		dataType: double
		lineageTag: 9d2b4349-8094-404f-b024-b969f96ca67b
		summarizeBy: sum
		sourceColumn: view_click_through_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column campaign_budget_amount
		dataType: double
		lineageTag: 7c8d2e9d-8f16-4ba5-b3a5-1eaa9bf31ae5
		summarizeBy: sum
		sourceColumn: campaign_budget_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column purchases_promoted
		dataType: int64
		formatString: 0
		lineageTag: 3af79a81-0d76-42fb-b835-f61194c2d137
		summarizeBy: sum
		sourceColumn: purchases_promoted

		annotation SummarizationSetBy = Automatic

	column new_to_brand_detail_page_view_rate
		dataType: double
		lineageTag: f43dfd47-31d5-4fb0-b248-b04bbc7feadd
		summarizeBy: sum
		sourceColumn: new_to_brand_detail_page_view_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column purchases
		dataType: int64
		formatString: 0
		lineageTag: 1921c938-c69c-43a5-89e3-3cdb8e0f0e87
		summarizeBy: sum
		sourceColumn: purchases

		annotation SummarizationSetBy = Automatic

	column campaign_id
		dataType: int64
		formatString: 0
		lineageTag: 415e556b-d2b9-4f86-b8cc-b416a17bb64c
		summarizeBy: none
		sourceColumn: campaign_id

		annotation SummarizationSetBy = Automatic

	column new_to_brand_purchases_percentage
		dataType: double
		lineageTag: c9e1ff82-c1e7-44a2-ac6e-e300bf03b85d
		summarizeBy: sum
		sourceColumn: new_to_brand_purchases_percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_promoted
		dataType: double
		lineageTag: ef011c68-e756-4ba6-9d0d-fbe9dcc89f97
		summarizeBy: sum
		sourceColumn: sales_promoted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column campaign_budget_currency_code
		dataType: string
		lineageTag: c06dbf69-a243-42fe-9333-b1128b28ce7c
		summarizeBy: none
		sourceColumn: campaign_budget_currency_code

		annotation SummarizationSetBy = Automatic

	column video_complete_views
		dataType: int64
		formatString: 0
		lineageTag: 250f6271-1a43-47ab-9fdf-dd3267bc172c
		summarizeBy: sum
		sourceColumn: video_complete_views

		annotation SummarizationSetBy = Automatic

	column sales_clicks
		dataType: double
		lineageTag: ed3ba93e-71ed-481d-8aff-6a8b738e2a1f
		summarizeBy: sum
		sourceColumn: sales_clicks

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column video_first_quartile_views
		dataType: int64
		formatString: 0
		lineageTag: 40d01ec1-74f8-4117-93a8-a3fe2a2c1230
		summarizeBy: sum
		sourceColumn: video_first_quartile_views

		annotation SummarizationSetBy = Automatic

	column new_to_brand_purchases_rate
		dataType: double
		lineageTag: 7c1e37d6-604a-42b9-be71-740f491579a9
		summarizeBy: sum
		sourceColumn: new_to_brand_purchases_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column units_sold_clicks
		dataType: int64
		formatString: 0
		lineageTag: e5ffd507-b6ff-4c05-a8df-2e791d38a99f
		summarizeBy: sum
		sourceColumn: units_sold_clicks

		annotation SummarizationSetBy = Automatic

	column branded_searches
		dataType: int64
		formatString: 0
		lineageTag: 4fa77922-8d27-4829-8897-386b17c00cb0
		summarizeBy: sum
		sourceColumn: branded_searches

		annotation SummarizationSetBy = Automatic

	column video_5_second_views
		dataType: int64
		formatString: 0
		lineageTag: e4e3c300-92c9-4228-a9d6-001b5f87714b
		summarizeBy: sum
		sourceColumn: video_5_second_views

		annotation SummarizationSetBy = Automatic

	column top_of_search_impression_share
		dataType: double
		lineageTag: ea1ba51f-648d-4430-bbc8-39de4eb11755
		summarizeBy: sum
		sourceColumn: top_of_search_impression_share

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column new_to_brand_ecpd_etail_page_view
		dataType: double
		lineageTag: e7f58408-6f69-4114-adcf-1c85c1405ae0
		summarizeBy: sum
		sourceColumn: new_to_brand_ecpd_etail_page_view

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column new_to_brand_purchases
		dataType: int64
		formatString: 0
		lineageTag: 54412970-f632-4059-97f5-fb86255f3f2e
		summarizeBy: sum
		sourceColumn: new_to_brand_purchases

		annotation SummarizationSetBy = Automatic

	column branded_searches_clicks
		dataType: int64
		formatString: 0
		lineageTag: 77bda5b0-d6f6-4d63-b718-4dd8dc30d4bc
		summarizeBy: sum
		sourceColumn: branded_searches_clicks

		annotation SummarizationSetBy = Automatic

	column new_to_brand_sales
		dataType: double
		lineageTag: 61df9a3f-062a-44de-9aa5-472a11e122bb
		summarizeBy: sum
		sourceColumn: new_to_brand_sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column new_to_brand_purchases_clicks
		dataType: int64
		formatString: 0
		lineageTag: e3c85b52-f146-47bd-ab89-c7cd3331b6e9
		summarizeBy: sum
		sourceColumn: new_to_brand_purchases_clicks

		annotation SummarizationSetBy = Automatic

	column campaign_budget_type
		dataType: string
		lineageTag: 5ee3da2c-8cc9-4dfd-b7aa-2e6d99d8db3d
		summarizeBy: none
		sourceColumn: campaign_budget_type

		annotation SummarizationSetBy = Automatic

	column add_to_cart_clicks
		dataType: int64
		formatString: 0
		lineageTag: 662dfd0a-0d4d-4060-8720-e85e834497b3
		summarizeBy: sum
		sourceColumn: add_to_cart_clicks

		annotation SummarizationSetBy = Automatic

	column video_unmutes
		dataType: int64
		formatString: 0
		lineageTag: fd897f61-5a32-4ed3-9101-51a2d834460f
		summarizeBy: sum
		sourceColumn: video_unmutes

		annotation SummarizationSetBy = Automatic

	column add_to_cart
		dataType: int64
		formatString: 0
		lineageTag: c507770c-d46f-496e-ae51-b0ca74d560e3
		summarizeBy: sum
		sourceColumn: add_to_cart

		annotation SummarizationSetBy = Automatic

	column video_third_quartile_views
		dataType: int64
		formatString: 0
		lineageTag: 63423ee3-d6aa-4be2-9d19-18e6883f7353
		summarizeBy: sum
		sourceColumn: video_third_quartile_views

		annotation SummarizationSetBy = Automatic

	column add_to_cart_rate
		dataType: double
		lineageTag: 49557682-a2a2-4428-b370-e7261b82134e
		summarizeBy: sum
		sourceColumn: add_to_cart_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cost
		dataType: double
		lineageTag: 0aba218a-4501-4dec-97a1-c43cb773b2d4
		summarizeBy: sum
		sourceColumn: cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column new_to_brand_detail_page_views_clicks
		dataType: int64
		formatString: 0
		lineageTag: 285e75f4-ecb8-4cba-bc2c-f3f35338146c
		summarizeBy: sum
		sourceColumn: new_to_brand_detail_page_views_clicks

		annotation SummarizationSetBy = Automatic

	column impressions
		dataType: int64
		formatString: 0
		lineageTag: d5023350-9d9d-48a1-b053-15660659a279
		summarizeBy: sum
		sourceColumn: impressions

		annotation SummarizationSetBy = Automatic

	column new_to_brand_units_sold
		dataType: int64
		formatString: 0
		lineageTag: 531158a1-691a-406e-af6a-e4c19dd92071
		summarizeBy: sum
		sourceColumn: new_to_brand_units_sold

		annotation SummarizationSetBy = Automatic

	column viewable_impressions
		dataType: int64
		formatString: 0
		lineageTag: 9907f80f-80b5-4292-9a74-b4260d653694
		summarizeBy: sum
		sourceColumn: viewable_impressions

		annotation SummarizationSetBy = Automatic

	column detail_page_views_clicks
		dataType: int64
		formatString: 0
		lineageTag: 100a158d-c15e-4e58-a97b-0e7e9d78a12b
		summarizeBy: sum
		sourceColumn: detail_page_views_clicks

		annotation SummarizationSetBy = Automatic

	column e_cpa_dd_to_cart
		dataType: double
		lineageTag: 94929e92-efc9-42fd-a558-b3422763b45f
		summarizeBy: sum
		sourceColumn: e_cpa_dd_to_cart

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column new_to_brand_detail_page_views
		dataType: int64
		formatString: 0
		lineageTag: 8b738ec3-ffec-48e9-a922-9a6445d93631
		summarizeBy: sum
		sourceColumn: new_to_brand_detail_page_views

		annotation SummarizationSetBy = Automatic

	column clicks
		dataType: int64
		formatString: 0
		lineageTag: 161bb40a-4e34-4d03-8963-95fa5ab0c4ce
		summarizeBy: sum
		sourceColumn: clicks

		annotation SummarizationSetBy = Automatic

	column video_midpoint_views
		dataType: int64
		formatString: 0
		lineageTag: 4b4a71ac-b687-46a4-84b8-6a14e78091d0
		summarizeBy: sum
		sourceColumn: video_midpoint_views

		annotation SummarizationSetBy = Automatic

	column video_5_second_view_rate
		dataType: double
		lineageTag: e1afd6f3-7feb-4228-900a-d53b23e14b00
		summarizeBy: sum
		sourceColumn: video_5_second_view_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column new_to_brand_units_sold_clicks
		dataType: int64
		formatString: 0
		lineageTag: 2b8271a7-3e79-4421-82d7-09dc2fc32218
		summarizeBy: sum
		sourceColumn: new_to_brand_units_sold_clicks

		annotation SummarizationSetBy = Automatic

	column new_to_brand_units_sold_percentage
		dataType: double
		lineageTag: 267234f2-ef64-4d7f-a544-a03e5cc70319
		summarizeBy: sum
		sourceColumn: new_to_brand_units_sold_percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column campaign_name
		dataType: string
		lineageTag: d19ac362-7779-4415-a262-84d2ecd2f433
		summarizeBy: none
		sourceColumn: campaign_name

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: fdf1b02c-ca7a-44cc-86a1-fb69cc5b99c0
		summarizeBy: none
		sourceColumn: created_at

		variation Variation
			isDefault
			relationship: 00e437f5-b55b-4c70-8fc0-10d849ed7e1b
			defaultHierarchy: LocalDateTable_929e918f-ed8e-47b9-9b60-f2e4278c046b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: e1979246-b17e-4e39-ad2a-1ce0d282e872
		summarizeBy: none
		sourceColumn: updated_at

		variation Variation
			isDefault
			relationship: 45da9196-5dac-4c53-a39e-63385955884f
			defaultHierarchy: LocalDateTable_68f39ee9-7671-4d98-9d62-c923673f0159.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column tenant_id
		dataType: int64
		formatString: 0
		lineageTag: 1dd1d690-e972-45fb-8ca2-1ca795358198
		summarizeBy: sum
		sourceColumn: tenant_id

		annotation SummarizationSetBy = Automatic

	partition 'SB campaign' = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("edgepify.app", "ecommerce", [HierarchicalNavigation=true]),
				    sponsored_brands = Source{[Schema="sponsored_brands"]}[Data],
				    campaign1 = sponsored_brands{[Name="campaign"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(campaign1,{{"date", type date}}),
				    #"Sorted Rows" = Table.Sort(#"Changed Type",{{"date", Order.Ascending}})
				in
				    #"Sorted Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

