table 'SD Historical Campaign Cost'
	isHidden
	lineageTag: 69ad3f3a-a047-42af-9ab6-a66c2e89bab7

	refreshPolicy
		policyType: basic
		rollingWindowGranularity: year
		rollingWindowPeriods: 5
		incrementalGranularity: month
		incrementalPeriods: 2
		sourceExpression =
			let
			    Source = GoogleBigQuery.Database(),
			    #"modern-sublime-383117" = Source{[Name="modern-sublime-383117"]}[Data],
			    sponsored_display_Schema = #"modern-sublime-383117"{[Name="sponsored_display",Kind="Schema"]}[Data],
			    portfolio_performance_summary_view = sponsored_display_Schema{[Name="portfolio_performance_summary_view",Kind="View"]}[Data],
			    #"Changed Type" = Table.TransformColumnTypes(portfolio_performance_summary_view,{{"date", type datetime}}),
			    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [date] >= RangeStart and [date] <= RangeEnd)
			in
			    #"Filtered Rows"

	column date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 44985b8b-f902-4399-a350-488823a61174
		summarizeBy: none
		sourceColumn: date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column marketplace
		dataType: string
		isHidden
		lineageTag: d08c0af6-ff78-4cce-a691-7b86e40227a1
		summarizeBy: none
		sourceColumn: marketplace

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column currency
		dataType: string
		isHidden
		lineageTag: 60aa7789-18dd-4093-bfb2-8e1357cba219
		summarizeBy: none
		sourceColumn: currency

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column portfolio_name
		dataType: string
		isHidden
		lineageTag: c764cda0-93cc-4d8a-8a13-ef01333e98ea
		summarizeBy: none
		sourceColumn: portfolio_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column product_code
		dataType: string
		isHidden
		lineageTag: 1ff131d7-5625-4998-a2be-3320539ae6b2
		summarizeBy: none
		sourceColumn: product_code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column cost
		dataType: double
		isHidden
		lineageTag: b13df212-8bad-47fb-b60a-011d7e2a6ab5
		summarizeBy: sum
		sourceColumn: cost

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column units_sold
		dataType: double
		isHidden
		lineageTag: e2f9db81-2712-40b7-add4-4cebf08aa528
		summarizeBy: sum
		sourceColumn: units_sold

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column clicks
		dataType: double
		isHidden
		lineageTag: 2f613f5d-d3b6-468e-948d-95211e0eaf4d
		summarizeBy: sum
		sourceColumn: clicks

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column impressions
		dataType: double
		isHidden
		lineageTag: 1e9b1e82-81ab-4fdb-9daa-02787318b1b6
		summarizeBy: sum
		sourceColumn: impressions

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'SD Historical Campaign Cost' = m
		mode: import
		source =
				let
				    Source = GoogleBigQuery.Database(),
				    #"modern-sublime-383117" = Source{[Name="modern-sublime-383117"]}[Data],
				    sponsored_display_Schema = #"modern-sublime-383117"{[Name="sponsored_display",Kind="Schema"]}[Data],
				    portfolio_performance_summary_view = sponsored_display_Schema{[Name="portfolio_performance_summary_view",Kind="View"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(portfolio_performance_summary_view,{{"date", type datetime}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [date] >= RangeStart and [date] <= RangeEnd)
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_IsMQueryFoldable = True

