table 'SP advertised_product'
	lineageTag: b58aab4c-61ed-4e38-a928-b8a1355f8317

	refreshPolicy
		policyType: basic
		rollingWindowGranularity: year
		rollingWindowPeriods: 5
		incrementalGranularity: month
		incrementalPeriods: 3
		pollingExpression = let Maxupdated_at = List.Max(#"SP advertised_product"[updated_at]), accountForNull = if Maxupdated_at = null then #datetime(1901, 01, 01, 00, 00, 00) else Maxupdated_at in accountForNull
		sourceExpression =
			let
			    Source = GoogleBigQuery.Database([Implementation="2.0"]),
			    #"modern-sublime-383117_Database" = Source{[Name="modern-sublime-383117",Kind="Database"]}[Data],
			    sponsored_products_Schema = #"modern-sublime-383117_Database"{[Name="sponsored_products",Kind="Schema"]}[Data],
			    advertised_product_Table = sponsored_products_Schema{[Name="advertised_product",Kind="Table"]}[Data],
			    #"Removed Columns" = Table.RemoveColumns(advertised_product_Table,{"_airbyte_raw_id", "_airbyte_extracted_at", "_airbyte_meta", "_airbyte_generation_id"}),
			    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"date", type datetime}}),
			    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [date] >= RangeStart and [date] <= RangeEnd)
			in
			    #"Filtered Rows"

	column cost
		dataType: double
		sourceProviderType: double
		lineageTag: 0d23e09a-c718-450b-9678-8f579152e85e
		summarizeBy: sum
		sourceColumn: cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: bef8c999-8882-470f-8bae-035f86f799f6
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column ad_id
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: d8b17d11-b358-413e-8a68-5c58eb196dc5
		summarizeBy: sum
		sourceColumn: ad_id

		annotation SummarizationSetBy = Automatic

	column spend
		dataType: double
		sourceProviderType: double
		lineageTag: 740ed727-1d18-44bc-aa0d-4277438ceaf2
		summarizeBy: sum
		sourceColumn: spend

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column clicks
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: bb27deb1-87c9-4ceb-b8f3-5bdb46ac6b4f
		summarizeBy: sum
		sourceColumn: clicks

		annotation SummarizationSetBy = Automatic

	column sales_1d
		dataType: double
		sourceProviderType: double
		lineageTag: 84259919-f392-4798-a1b6-47cbfbf9ce66
		summarizeBy: sum
		sourceColumn: sales_1d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_7d
		dataType: double
		sourceProviderType: double
		lineageTag: 8b9697b5-6fc0-4ddc-be2e-68b0589ac32e
		summarizeBy: sum
		sourceColumn: sales_7d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_14d
		dataType: double
		sourceProviderType: double
		lineageTag: 6fe14bbe-dd6a-4e89-acc9-9ee5e0ae1e73
		summarizeBy: sum
		sourceColumn: sales_14d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_30d
		dataType: double
		sourceProviderType: double
		lineageTag: d576218a-205f-49f6-8e19-6a7f5da16d6c
		summarizeBy: sum
		sourceColumn: sales_30d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tenant_id
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 3d124118-87d7-4c8e-9519-89687d712ed3
		summarizeBy: sum
		sourceColumn: tenant_id

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 0585892c-fee5-40f4-92cb-b94b746721da
		summarizeBy: none
		sourceColumn: created_at

		variation Variation
			isDefault
			relationship: 99d4cf48-9dce-453a-af1a-9856150ec7f9
			defaultHierarchy: LocalDateTable_0246d5fb-33b8-4793-981c-fd78e39eacbf.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column updated_at
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 05cff794-3497-4ba9-9252-cef0362747e8
		summarizeBy: none
		sourceColumn: updated_at

		variation Variation
			isDefault
			relationship: 2f97c2aa-7153-4568-ae0c-6ee608d059b1
			defaultHierarchy: LocalDateTable_0df5734d-1b9d-4868-8c51-2524c2a33a38.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column ad_group_id
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: c3c61f05-ccdc-4cba-a4eb-211268fd8b1b
		summarizeBy: sum
		sourceColumn: ad_group_id

		annotation SummarizationSetBy = Automatic

	column campaign_id
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: fc54a1ae-e564-4f2a-a97e-653c5829cc82
		summarizeBy: sum
		sourceColumn: campaign_id

		annotation SummarizationSetBy = Automatic

	column impressions
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 9517691c-810d-42fd-aa9f-b74a9dbfa9dc
		summarizeBy: sum
		sourceColumn: impressions

		annotation SummarizationSetBy = Automatic

	column marketplace
		dataType: string
		sourceProviderType: nvarchar(16384)
		lineageTag: 24099196-af9e-4594-a2da-c4aa2026b302
		summarizeBy: none
		sourceColumn: marketplace

		annotation SummarizationSetBy = Automatic

	column portfolio_id
		dataType: double
		sourceProviderType: double
		lineageTag: 04fb203e-134b-4ee7-8cd3-b9eb892cc14d
		summarizeBy: sum
		sourceColumn: portfolio_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column purchases_1d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 5008d653-cda8-4689-a4fd-76c4ad243b59
		summarizeBy: sum
		sourceColumn: purchases_1d

		annotation SummarizationSetBy = Automatic

	column purchases_7d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: f5a27bd1-32f7-400f-acd2-96e29118d955
		summarizeBy: sum
		sourceColumn: purchases_7d

		annotation SummarizationSetBy = Automatic

	column ad_group_name
		dataType: string
		sourceProviderType: nvarchar(16384)
		lineageTag: adb6bd16-fcce-42ce-8f57-cccbdeac58bd
		summarizeBy: none
		sourceColumn: ad_group_name

		annotation SummarizationSetBy = Automatic

	column campaign_name
		dataType: string
		sourceProviderType: nvarchar(16384)
		lineageTag: 973246d2-1056-44db-bc8c-dda9391e975b
		summarizeBy: none
		sourceColumn: campaign_name

		annotation SummarizationSetBy = Automatic

	column purchases_14d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 895b5a76-19cf-4e93-bed9-c1654e8f7139
		summarizeBy: sum
		sourceColumn: purchases_14d

		annotation SummarizationSetBy = Automatic

	column purchases_30d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: bf156304-713c-43c2-919c-babd1060ae55
		summarizeBy: sum
		sourceColumn: purchases_30d

		annotation SummarizationSetBy = Automatic

	column acos_clicks_7d
		dataType: double
		sourceProviderType: double
		lineageTag: dab4b5ec-c0c4-4b57-8414-8277edec9b7b
		summarizeBy: sum
		sourceColumn: acos_clicks_7d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column advertised_sku
		dataType: string
		sourceProviderType: nvarchar(16384)
		lineageTag: c8fc09dd-8119-4d51-bbb6-73b252a7dbe1
		summarizeBy: none
		sourceColumn: advertised_sku

		annotation SummarizationSetBy = Automatic

	column cost_per_click
		dataType: double
		sourceProviderType: double
		lineageTag: e1ed0fcf-2904-4173-95c4-8817bb1f287a
		summarizeBy: sum
		sourceColumn: cost_per_click

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column roas_clicks_7d
		dataType: double
		sourceProviderType: double
		lineageTag: ececfca5-8dbc-4b1a-9041-877ac4933798
		summarizeBy: sum
		sourceColumn: roas_clicks_7d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column acos_clicks_14d
		dataType: double
		sourceProviderType: double
		lineageTag: b106d65a-e9d0-4f22-8b80-6696795b8499
		summarizeBy: sum
		sourceColumn: acos_clicks_14d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column advertised_asin
		dataType: string
		sourceProviderType: nvarchar(16384)
		lineageTag: c4cd06ef-10b4-4359-ac05-cf7b62857e05
		summarizeBy: none
		sourceColumn: advertised_asin

		annotation SummarizationSetBy = Automatic

	column campaign_status
		dataType: string
		sourceProviderType: nvarchar(16384)
		lineageTag: 9b8b2842-e84c-440c-9d43-c0a0c95c9a70
		summarizeBy: none
		sourceColumn: campaign_status

		annotation SummarizationSetBy = Automatic

	column roas_clicks_14d
		dataType: double
		sourceProviderType: double
		lineageTag: e41c09e1-830f-4227-8051-cdf9abf28a74
		summarizeBy: sum
		sourceColumn: roas_clicks_14d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column click_through_rate
		dataType: double
		sourceProviderType: double
		lineageTag: eb0dd20a-77e3-4cb6-83e7-bad7b5eca673
		summarizeBy: sum
		sourceColumn: click_through_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_other_sku_7d
		dataType: double
		sourceProviderType: double
		lineageTag: e9c01458-f49c-453a-9576-297959e755af
		summarizeBy: sum
		sourceColumn: sales_other_sku_7d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column campaign_budget_type
		dataType: string
		sourceProviderType: nvarchar(16384)
		lineageTag: 072caac9-82d2-4198-9fbd-6366ec27cbb3
		summarizeBy: none
		sourceColumn: campaign_budget_type

		annotation SummarizationSetBy = Automatic

	column units_sold_clicks_1d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 3a603247-4895-4584-9176-6d0c922fb884
		summarizeBy: sum
		sourceColumn: units_sold_clicks_1d

		annotation SummarizationSetBy = Automatic

	column units_sold_clicks_7d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: eea7081c-041a-47d4-a145-7cfa3b7db3cf
		summarizeBy: sum
		sourceColumn: units_sold_clicks_7d

		annotation SummarizationSetBy = Automatic

	column purchases_same_sku_1d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: e25f7014-5c20-46e0-9cb7-de2f47f764fa
		summarizeBy: sum
		sourceColumn: purchases_same_sku_1d

		annotation SummarizationSetBy = Automatic

	column purchases_same_sku_7d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 0b020e87-2113-4620-a8e6-8a8c03bf979a
		summarizeBy: sum
		sourceColumn: purchases_same_sku_7d

		annotation SummarizationSetBy = Automatic

	column units_sold_clicks_14d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: a768a7ab-3a77-4532-bb3a-7c00374e8ba3
		summarizeBy: sum
		sourceColumn: units_sold_clicks_14d

		annotation SummarizationSetBy = Automatic

	column units_sold_clicks_30d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 51f56df6-7dc5-4804-80b6-e7eb15bb8ffb
		summarizeBy: sum
		sourceColumn: units_sold_clicks_30d

		annotation SummarizationSetBy = Automatic

	column campaign_budget_amount
		dataType: double
		sourceProviderType: double
		lineageTag: b8b5dffb-3a9e-46c1-93a7-d39fa54d2475
		summarizeBy: sum
		sourceColumn: campaign_budget_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column purchases_same_sku_14d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: dde7f6ce-66c5-42a2-9b62-2359ece88def
		summarizeBy: sum
		sourceColumn: purchases_same_sku_14d

		annotation SummarizationSetBy = Automatic

	column purchases_same_sku_30d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: ad56d53a-4f28-44d0-b6f8-31a7ae52e9d1
		summarizeBy: sum
		sourceColumn: purchases_same_sku_30d

		annotation SummarizationSetBy = Automatic

	column units_sold_same_sku_1d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 2b548552-3248-47b4-a382-3b13aa72b921
		summarizeBy: sum
		sourceColumn: units_sold_same_sku_1d

		annotation SummarizationSetBy = Automatic

	column units_sold_same_sku_7d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: d67d39e1-a0db-4fcd-aaa0-b95588d69c87
		summarizeBy: sum
		sourceColumn: units_sold_same_sku_7d

		annotation SummarizationSetBy = Automatic

	column units_sold_other_sku_7d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 41926fe7-9185-4209-bed7-ff5e742f14af
		summarizeBy: sum
		sourceColumn: units_sold_other_sku_7d

		annotation SummarizationSetBy = Automatic

	column units_sold_same_sku_14d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 90787775-e8ab-46f0-b7b2-133337890bd9
		summarizeBy: sum
		sourceColumn: units_sold_same_sku_14d

		annotation SummarizationSetBy = Automatic

	column units_sold_same_sku_30d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: dbc17968-c56a-4cf0-aeac-a7cd7eef65a9
		summarizeBy: sum
		sourceColumn: units_sold_same_sku_30d

		annotation SummarizationSetBy = Automatic

	column attributed_sales_same_sku_1d
		dataType: double
		sourceProviderType: double
		lineageTag: be1386f0-8681-4e86-b6cf-06b6934ee126
		summarizeBy: sum
		sourceColumn: attributed_sales_same_sku_1d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column attributed_sales_same_sku_7d
		dataType: double
		sourceProviderType: double
		lineageTag: b45da9f7-da5a-47cd-ba97-8d87a327fd2d
		summarizeBy: sum
		sourceColumn: attributed_sales_same_sku_7d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column attributed_sales_same_sku_14d
		dataType: double
		sourceProviderType: double
		lineageTag: 96bfe0f7-0205-4fb2-804a-e47818a42cf1
		summarizeBy: sum
		sourceColumn: attributed_sales_same_sku_14d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column attributed_sales_same_sku_30d
		dataType: double
		sourceProviderType: double
		lineageTag: 46ed22b1-cd23-45aa-adbc-af12173dba59
		summarizeBy: sum
		sourceColumn: attributed_sales_same_sku_30d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column campaign_budget_currency_code
		dataType: string
		sourceProviderType: nvarchar(16384)
		lineageTag: 0614ff37-6c60-4989-867c-866f389647cc
		summarizeBy: none
		sourceColumn: campaign_budget_currency_code

		annotation SummarizationSetBy = Automatic

	column kindle_edition_normalized_pages_read_14d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 7c71df56-ea7e-49c1-a9f8-3b00a95d8afd
		summarizeBy: sum
		sourceColumn: kindle_edition_normalized_pages_read_14d

		annotation SummarizationSetBy = Automatic

	column kindle_edition_normalized_pages_royalties_14d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: a05537e5-1569-4945-9a7f-b1f19d962f68
		summarizeBy: sum
		sourceColumn: kindle_edition_normalized_pages_royalties_14d

		annotation SummarizationSetBy = Automatic

	partition 'SP advertised_product' = m
		mode: import
		source =
				let
				    Source = GoogleBigQuery.Database([Implementation="2.0"]),
				    #"modern-sublime-383117_Database" = Source{[Name="modern-sublime-383117",Kind="Database"]}[Data],
				    sponsored_products_Schema = #"modern-sublime-383117_Database"{[Name="sponsored_products",Kind="Schema"]}[Data],
				    advertised_product_Table = sponsored_products_Schema{[Name="advertised_product",Kind="Table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(advertised_product_Table,{"_airbyte_raw_id", "_airbyte_extracted_at", "_airbyte_meta", "_airbyte_generation_id"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"date", type datetime}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [date] >= RangeStart and [date] <= RangeEnd)
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation PBI_IsMQueryFoldable = True

