table 'SP Historical Campaign Cost'
	lineageTag: 6f5aba7d-ef79-4752-82ac-e0071352b3c8

	column date
		dataType: dateTime
		formatString: General Date
		lineageTag: 42d9ef9f-adcd-4b90-af7b-17c0b9d14b36
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column marketplace
		dataType: string
		lineageTag: d17ef9fb-799f-4153-b953-ab7e4008d929
		summarizeBy: none
		sourceColumn: marketplace

		annotation SummarizationSetBy = Automatic

	column total_cost
		dataType: double
		lineageTag: b5bdafe8-049c-419b-9d96-8d1ec247ec13
		summarizeBy: sum
		sourceColumn: total_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_units_sold_clicks_7d
		dataType: int64
		formatString: 0
		lineageTag: c96d981c-5af7-4233-91d7-c745d424d66d
		summarizeBy: sum
		sourceColumn: total_units_sold_clicks_7d

		annotation SummarizationSetBy = Automatic

	column total_clicks
		dataType: int64
		formatString: 0
		lineageTag: 76d014f3-64ea-46d3-bfb1-32d5be07ac29
		summarizeBy: sum
		sourceColumn: total_clicks

		annotation SummarizationSetBy = Automatic

	column total_impressions
		dataType: int64
		formatString: 0
		lineageTag: 5ce0724c-8b9a-436c-b191-8ba7c2bbd6b9
		summarizeBy: sum
		sourceColumn: total_impressions

		annotation SummarizationSetBy = Automatic

	column sales_7d
		dataType: double
		lineageTag: 3cc5dd68-0882-4e17-8621-37a072c4d994
		summarizeBy: sum
		sourceColumn: sales_7d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column portfolio_id
		dataType: double
		lineageTag: 6e09773e-34d1-4c84-a37e-cfc41d47617e
		summarizeBy: sum
		sourceColumn: portfolio_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column currency
		dataType: string
		lineageTag: bdb897a7-622e-44c2-b7ab-2b7b4ae75c6a
		summarizeBy: none
		sourceColumn: currency

		annotation SummarizationSetBy = Automatic

	column 'portfolio name' = LOOKUPVALUE('Dim Amazon Portfolios'[name], 'Dim Amazon Portfolios'[portfolio_id], [portfolio_id])
		lineageTag: e09d7a67-a131-498a-a1f2-2762eb8690f3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column portfolio_name
		dataType: string
		lineageTag: aeda5444-3d46-442a-882e-c0ee863805be
		summarizeBy: none
		sourceColumn: portfolio_name

		annotation SummarizationSetBy = Automatic

	column parent_code
		dataType: string
		lineageTag: 773bc9fb-a425-4bb2-8815-ad85064ee380
		summarizeBy: none
		sourceColumn: parent_code

		annotation SummarizationSetBy = Automatic

	partition 'SP Historical Campaign Cost' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(PostgreSQL.Database("edgepify.app", "ecommerce", [CommandTimeout=#duration(0, 0, 5, 0)]), "-- API data source. (04-02-2023 to present)#(lf)select#(lf)    t1.date,#(lf)    t1.marketplace,#(lf)    t2.portfolio_id,#(lf)    t3.name portfolio_name,#(lf)    t1.campaign_budget_currency_code currency,#(lf)    sum(t1.cost) total_cost,#(lf)    sum(t1.units_sold_clicks_7d) total_units_sold_clicks_7d,#(lf)    sum(t1.clicks) total_clicks,#(lf)    sum(t1.impressions) total_impressions,#(lf)    sum(t1.sales_7d) sales_7d#(lf)from sponsored_products.campaign t1#(lf)left join (select distinct on (campaign_id)#(lf)            campaign_id,#(lf)            portfolio_id#(lf)        from sponsored_products.targeting#(lf)        order by campaign_id, date desc) as t2#(lf)    on t1.campaign_id = t2.campaign_id#(lf)left join amazon_advertising_portfolios t3#(lf)    on t2.portfolio_id = t3.portfolio_id#(lf)group by t1.date, t1.marketplace, t2.portfolio_id, t3.name, t1.campaign_budget_currency_code#(lf)having sum(t1.impressions) > 0#(lf)#(lf)UNION#(lf)#(lf)-- Advertising reports data source. (06-27-2022 to 2023-04-01)#(lf)select#(lf)    t1.date,#(lf)    t1.marketplace,#(lf)    t2.portfolio_id,#(lf)    t3.name portfolio_name,#(lf)    t1.currency,#(lf)    sum(t1.spend) total_cost,#(lf)    sum(t1.""7_day_total_orders"") total_units_sold_clicks_7d,#(lf)    sum(t1.clicks) total_clicks,#(lf)    sum(t1.impressions) total_impressions,#(lf)    sum(t1.""7_day_total_sales"") sales_7d#(lf)from sponsored_products.campaign_console t1#(lf)left join amazon_advertising_portfolios t2#(lf)    on t1.portfolio_name = t2.name and t1.marketplace = t2.marketplace#(lf)left join amazon_advertising_portfolios t3#(lf)    on t2.portfolio_id = t3.portfolio_id#(lf)where t1.date < '04-02-2023'#(lf)group by t1.date, t1.marketplace, t2.portfolio_id, t3.name, t1.currency#(lf)order by date asc, marketplace desc", null, [EnableFolding=true]),
				    #"Inserted Text Before Delimiter" = Table.AddColumn(Source, "Text Before Delimiter", each Text.BeforeDelimiter([portfolio_name], "-", 1), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Text Before Delimiter",{{"Text Before Delimiter", "parent_code"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

