table 'SP purchased_product'
	lineageTag: 35022c5c-585b-4aee-81ef-9362737c6324

	refreshPolicy
		policyType: basic
		rollingWindowGranularity: year
		rollingWindowPeriods: 5
		incrementalGranularity: month
		incrementalPeriods: 3
		pollingExpression = let Maxupdated_at = List.Max(#"SP purchased_product"[updated_at]), accountForNull = if Maxupdated_at = null then #datetime(1901, 01, 01, 00, 00, 00) else Maxupdated_at in accountForNull
		sourceExpression =
			let
			    Source = GoogleBigQuery.Database([Implementation="2.0"]),
			    #"modern-sublime-383117_Database" = Source{[Name="modern-sublime-383117",Kind="Database"]}[Data],
			    sponsored_products_Schema = #"modern-sublime-383117_Database"{[Name="sponsored_products",Kind="Schema"]}[Data],
			    purchased_product_Table = sponsored_products_Schema{[Name="purchased_product",Kind="Table"]}[Data],
			    #"Removed Columns" = Table.RemoveColumns(purchased_product_Table,{"_airbyte_raw_id", "_airbyte_extracted_at", "_airbyte_meta", "_airbyte_generation_id"}),
			    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"date", type datetime}}),
			    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [date] >= RangeStart and [date] <= RangeEnd)
			in
			    #"Filtered Rows"

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 67db7ecb-ceed-4a53-b7d7-a567a77285e9
		summarizeBy: none
		sourceColumn: date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column keyword
		dataType: string
		sourceProviderType: nvarchar(16384)
		lineageTag: 1a2c9578-f18f-4564-adea-3ae686848fb5
		summarizeBy: none
		sourceColumn: keyword

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column sales_1d
		dataType: double
		sourceProviderType: double
		lineageTag: 4fd0aea2-7cf6-46c6-8ea3-eb522a50a366
		summarizeBy: sum
		sourceColumn: sales_1d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_7d
		dataType: double
		sourceProviderType: double
		lineageTag: 537f0623-0eda-4a32-8677-f28c68003f69
		summarizeBy: sum
		sourceColumn: sales_7d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_14d
		dataType: double
		sourceProviderType: double
		lineageTag: eb8aab4f-3d58-46ec-835a-1e5372292826
		summarizeBy: sum
		sourceColumn: sales_14d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_30d
		dataType: double
		sourceProviderType: double
		lineageTag: c6796b9c-398f-4ab6-b7e5-78d5faf36732
		summarizeBy: sum
		sourceColumn: sales_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column tenant_id
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 2f029818-0d4c-4610-aec9-de7154aa7521
		summarizeBy: sum
		sourceColumn: tenant_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column created_at
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: a54600e5-c37d-4671-93f6-ef4739122324
		summarizeBy: none
		sourceColumn: created_at

		variation Variation
			isDefault
			relationship: 3cd3ffdb-9f9a-4f20-bbad-37e78d91a125
			defaultHierarchy: LocalDateTable_70d0cd75-92e5-408a-ad90-4b23d52da6b4.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column keyword_id
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 4f9918e5-94a0-4d0c-9acc-4e0482a81ea6
		summarizeBy: sum
		sourceColumn: keyword_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column match_type
		dataType: string
		sourceProviderType: nvarchar(16384)
		lineageTag: a6da19d2-e8e0-403d-93af-5c4a2b12e752
		summarizeBy: none
		sourceColumn: match_type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column updated_at
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 8e2a4a3b-b005-45c9-aa29-f1cd95fac010
		summarizeBy: none
		sourceColumn: updated_at

		variation Variation
			isDefault
			relationship: 84def41c-278e-48c9-84b1-a35a96f3fb39
			defaultHierarchy: LocalDateTable_e832a7c6-497f-4fc6-b9ab-9c2d43a1918e.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ad_group_id
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: de09310c-891b-42ea-9ec2-ed6c15598dc2
		summarizeBy: sum
		sourceColumn: ad_group_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column campaign_id
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 65edeb33-0d73-4d46-b5e6-6ddfdbe99bed
		summarizeBy: sum
		sourceColumn: campaign_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column marketplace
		dataType: string
		sourceProviderType: nvarchar(16384)
		lineageTag: 1e51bd64-fb67-49b1-a269-25eeeaf798e6
		summarizeBy: none
		sourceColumn: marketplace

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column keyword_type
		dataType: string
		sourceProviderType: nvarchar(16384)
		lineageTag: 972eaa6a-ff0a-4d04-97d0-2d166028ea0f
		summarizeBy: none
		sourceColumn: keyword_type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column portfolio_id
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 94053d91-74f0-4b6e-bd46-96ff6f69bace
		summarizeBy: sum
		sourceColumn: portfolio_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column purchases_1d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 31434e2c-f86f-4c4b-a298-735bf107d010
		summarizeBy: sum
		sourceColumn: purchases_1d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column purchases_7d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 545afe3c-2cbc-4eb4-9a46-d592849ac23f
		summarizeBy: sum
		sourceColumn: purchases_7d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ad_group_name
		dataType: string
		sourceProviderType: nvarchar(16384)
		lineageTag: 23ec9794-59a0-469b-80b9-2df6599eccfa
		summarizeBy: none
		sourceColumn: ad_group_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column campaign_name
		dataType: string
		sourceProviderType: nvarchar(16384)
		lineageTag: 0b46f662-02cd-43bd-a8ff-b50bd7dcd7d9
		summarizeBy: none
		sourceColumn: campaign_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column purchases_14d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: cc111d27-9c94-45e1-a1c8-24c3c10dd9f6
		summarizeBy: sum
		sourceColumn: purchases_14d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column purchases_30d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: fcfa46a0-b905-4246-b5ac-81a6ece2d15e
		summarizeBy: sum
		sourceColumn: purchases_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column advertised_sku
		dataType: string
		sourceProviderType: nvarchar(16384)
		lineageTag: aae2f647-cfd3-421a-bde9-4888c979bcb4
		summarizeBy: none
		sourceColumn: advertised_sku

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column purchased_asin
		dataType: string
		sourceProviderType: nvarchar(16384)
		lineageTag: 104da3e4-3755-4283-a006-0c37740f66b0
		summarizeBy: none
		sourceColumn: purchased_asin

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column advertised_asin
		dataType: string
		sourceProviderType: nvarchar(16384)
		lineageTag: ebd56414-7222-46aa-b439-0edea5eea4b5
		summarizeBy: none
		sourceColumn: advertised_asin

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column sales_other_sku_1d
		dataType: double
		sourceProviderType: double
		lineageTag: 3db54af3-0e30-4149-b69b-c71d8b6b7dea
		summarizeBy: sum
		sourceColumn: sales_other_sku_1d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_other_sku_7d
		dataType: double
		sourceProviderType: double
		lineageTag: 5d40344b-762c-431f-8f80-404e0e63c4c8
		summarizeBy: sum
		sourceColumn: sales_other_sku_7d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_other_sku_14d
		dataType: double
		sourceProviderType: double
		lineageTag: 6900fd96-e7fd-4f21-bd3b-43e9975068d7
		summarizeBy: sum
		sourceColumn: sales_other_sku_14d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_other_sku_30d
		dataType: double
		sourceProviderType: double
		lineageTag: 4dff473f-aad4-433c-a7c2-087acb2ceb61
		summarizeBy: sum
		sourceColumn: sales_other_sku_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column units_sold_clicks_1d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: c3579aa0-b4dc-46b3-a11f-9c2ccf3558c3
		summarizeBy: sum
		sourceColumn: units_sold_clicks_1d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column units_sold_clicks_7d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: bc97d521-00d7-455c-9aa1-b5aa23c263f2
		summarizeBy: sum
		sourceColumn: units_sold_clicks_7d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column units_sold_clicks_14d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: aba9c845-e2f5-4cce-989b-a98a96f733c5
		summarizeBy: sum
		sourceColumn: units_sold_clicks_14d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column units_sold_clicks_30d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 6c2cc1a4-ddc1-4341-ba72-eb17a7ee09e0
		summarizeBy: sum
		sourceColumn: units_sold_clicks_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column purchases_other_sku_1d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 03522adc-e50c-4fbf-b4e7-fc5ebe93e983
		summarizeBy: sum
		sourceColumn: purchases_other_sku_1d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column purchases_other_sku_7d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 085bf7bc-a128-489a-8773-8011c971f1ce
		summarizeBy: sum
		sourceColumn: purchases_other_sku_7d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column purchases_other_sku_14d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 41195e41-6dc6-4dd6-83b4-673a45b81b1b
		summarizeBy: sum
		sourceColumn: purchases_other_sku_14d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column purchases_other_sku_30d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: ddf18bde-760c-4100-80a6-551d35c25634
		summarizeBy: sum
		sourceColumn: purchases_other_sku_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column units_sold_other_sku_1d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: b4df573e-9b89-4423-8810-737142961f60
		summarizeBy: sum
		sourceColumn: units_sold_other_sku_1d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column units_sold_other_sku_7d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: adf83ebc-24e5-40bb-9017-9efeb80bb752
		summarizeBy: sum
		sourceColumn: units_sold_other_sku_7d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column units_sold_other_sku_14d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 5ab2d1b4-27ed-430a-8098-537e371879f9
		summarizeBy: sum
		sourceColumn: units_sold_other_sku_14d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column units_sold_other_sku_30d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: bf3d7790-37a4-4a4e-baec-5175aa07031d
		summarizeBy: sum
		sourceColumn: units_sold_other_sku_30d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column campaign_budget_currency_code
		dataType: string
		sourceProviderType: nvarchar(16384)
		lineageTag: 62e7c835-c6ac-4dd9-8626-ebfec0805724
		summarizeBy: none
		sourceColumn: campaign_budget_currency_code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column kindle_edition_normalized_pages_read_14d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 73da88ad-b30b-4c2b-80bd-54ff3cce9085
		summarizeBy: sum
		sourceColumn: kindle_edition_normalized_pages_read_14d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column kindle_edition_normalized_pages_royalties_14d
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		lineageTag: 4ddc214d-0254-48ce-a222-a7d79c2ee3eb
		summarizeBy: sum
		sourceColumn: kindle_edition_normalized_pages_royalties_14d

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'SP purchased_product' = m
		mode: import
		source =
				let
				    Source = GoogleBigQuery.Database([Implementation="2.0"]),
				    #"modern-sublime-383117_Database" = Source{[Name="modern-sublime-383117",Kind="Database"]}[Data],
				    sponsored_products_Schema = #"modern-sublime-383117_Database"{[Name="sponsored_products",Kind="Schema"]}[Data],
				    purchased_product_Table = sponsored_products_Schema{[Name="purchased_product",Kind="Table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(purchased_product_Table,{"_airbyte_raw_id", "_airbyte_extracted_at", "_airbyte_meta", "_airbyte_generation_id"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"date", type datetime}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [date] >= RangeStart and [date] <= RangeEnd)
				in
				    #"Filtered Rows"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

	annotation PBI_IsMQueryFoldable = True

