table 'SP search_term'
	lineageTag: 998abc84-c53a-4f36-81de-14df7bbc9bd4

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 924f0b81-f98d-4e17-9b16-dc30c39614aa
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column attributed_sales_same_sku_1d
		dataType: double
		lineageTag: d0ae1714-0037-4afd-ab70-3824c982a403
		summarizeBy: sum
		sourceColumn: attributed_sales_same_sku_1d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column roas_clicks_14d
		dataType: double
		lineageTag: 60f65d44-c275-4008-a0b1-a465f022c6a2
		summarizeBy: sum
		sourceColumn: roas_clicks_14d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column units_sold_clicks_1d
		dataType: int64
		formatString: 0
		lineageTag: e1548967-c1f2-4eb7-a05b-44b7e3f0c1e1
		summarizeBy: sum
		sourceColumn: units_sold_clicks_1d

		annotation SummarizationSetBy = Automatic

	column match_type
		dataType: string
		lineageTag: cecdc385-e4fe-4e9c-9809-4b0961c56ba0
		summarizeBy: none
		sourceColumn: match_type

		annotation SummarizationSetBy = Automatic

	column attributed_sales_same_sku_14d
		dataType: double
		lineageTag: 73a75816-c969-42cf-82f4-b030982ee222
		summarizeBy: sum
		sourceColumn: attributed_sales_same_sku_14d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_7d
		dataType: double
		lineageTag: 35a4cede-0025-4b3c-9daa-5659e5801870
		summarizeBy: sum
		sourceColumn: sales_7d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column attributed_sales_same_sku_30d
		dataType: double
		lineageTag: 5d309dc9-bde0-42de-95ad-76b1c7cb23c9
		summarizeBy: sum
		sourceColumn: attributed_sales_same_sku_30d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column kindle_edition_normalized_pages_royalties_14d
		dataType: int64
		formatString: 0
		lineageTag: 735c4a82-0f29-4484-9dd1-7f0f789f03f5
		summarizeBy: sum
		sourceColumn: kindle_edition_normalized_pages_royalties_14d

		annotation SummarizationSetBy = Automatic

	column search_term
		dataType: string
		lineageTag: 35a95bab-421c-4a0a-b73f-3c239543f9f9
		summarizeBy: none
		sourceColumn: search_term

		annotation SummarizationSetBy = Automatic

	column units_sold_same_sku_1d
		dataType: int64
		formatString: 0
		lineageTag: c277cc44-fbae-47bb-8db9-8957073751db
		summarizeBy: sum
		sourceColumn: units_sold_same_sku_1d

		annotation SummarizationSetBy = Automatic

	column keyword
		dataType: string
		lineageTag: de5ab952-c1b3-4cf4-a661-8409565e1ec3
		summarizeBy: none
		sourceColumn: keyword

		annotation SummarizationSetBy = Automatic

	column sales_other_sku_7d
		dataType: double
		lineageTag: 2f5fd7a0-fcd3-4419-9680-8d643cd36ded
		summarizeBy: sum
		sourceColumn: sales_other_sku_7d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column purchases_same_sku_7d
		dataType: int64
		formatString: 0
		lineageTag: 809b1440-ea79-448c-97ae-5239d813d515
		summarizeBy: sum
		sourceColumn: purchases_same_sku_7d

		annotation SummarizationSetBy = Automatic

	column campaign_budget_amount
		dataType: double
		lineageTag: e49fa3b8-8fa4-4bd7-95da-05b4c93041c4
		summarizeBy: sum
		sourceColumn: campaign_budget_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column purchases_7d
		dataType: int64
		formatString: 0
		lineageTag: abc45070-7971-420e-9484-2d1c490718c9
		summarizeBy: sum
		sourceColumn: purchases_7d

		annotation SummarizationSetBy = Automatic

	column units_sold_same_sku_30d
		dataType: int64
		formatString: 0
		lineageTag: 28d30e84-bdb9-426d-9b44-f7326aa4eeb6
		summarizeBy: sum
		sourceColumn: units_sold_same_sku_30d

		annotation SummarizationSetBy = Automatic

	column cost_per_click
		dataType: double
		lineageTag: da616e78-7eef-4477-8652-17eb42a9e02d
		summarizeBy: sum
		sourceColumn: cost_per_click

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column units_sold_clicks_14d
		dataType: int64
		formatString: 0
		lineageTag: 064e8d28-d553-49cb-800b-4d69bf4b40df
		summarizeBy: sum
		sourceColumn: units_sold_clicks_14d

		annotation SummarizationSetBy = Automatic

	column ad_group_name
		dataType: string
		lineageTag: 6e4c3927-9c2c-4f96-96ab-63ad56f0f922
		summarizeBy: none
		sourceColumn: ad_group_name

		annotation SummarizationSetBy = Automatic

	column campaign_id
		dataType: int64
		formatString: 0
		lineageTag: 74cae27d-0db8-409b-a8a7-97d642ba160e
		summarizeBy: none
		sourceColumn: campaign_id

		annotation SummarizationSetBy = Automatic

	column click_through_rate
		dataType: double
		lineageTag: 5f6d098e-cb3e-400a-b5e4-d7846253908e
		summarizeBy: sum
		sourceColumn: click_through_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column kindle_edition_normalized_pages_read_14d
		dataType: int64
		formatString: 0
		lineageTag: 492cac3a-e6aa-4e36-9b6b-1e1b315004a2
		summarizeBy: sum
		sourceColumn: kindle_edition_normalized_pages_read_14d

		annotation SummarizationSetBy = Automatic

	column acos_clicks_14d
		dataType: double
		lineageTag: b01bb9a7-5af6-48fd-8aba-013db49eb118
		summarizeBy: sum
		sourceColumn: acos_clicks_14d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column units_sold_clicks_30d
		dataType: int64
		formatString: 0
		lineageTag: 1c871c40-4c04-48cd-a355-0035be5d6001
		summarizeBy: sum
		sourceColumn: units_sold_clicks_30d

		annotation SummarizationSetBy = Automatic

	column portfolio_id
		dataType: double
		lineageTag: 94828fda-ebce-442c-a92f-a19d45d2f4a1
		summarizeBy: sum
		sourceColumn: portfolio_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column campaign_budget_currency_code
		dataType: string
		lineageTag: 777d7730-59cd-4077-b2e9-20283ea2506a
		summarizeBy: none
		sourceColumn: campaign_budget_currency_code

		annotation SummarizationSetBy = Automatic

	column roas_clicks_7d
		dataType: double
		lineageTag: 2ddd34d9-086d-432b-991b-5ca6eac0f983
		summarizeBy: sum
		sourceColumn: roas_clicks_7d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column units_sold_same_sku_14d
		dataType: int64
		formatString: 0
		lineageTag: 0926594d-9532-41eb-9773-16db27826a2a
		summarizeBy: sum
		sourceColumn: units_sold_same_sku_14d

		annotation SummarizationSetBy = Automatic

	column units_sold_clicks_7d
		dataType: int64
		formatString: 0
		lineageTag: 14ee3f65-cd5b-4888-a308-04348584e880
		summarizeBy: sum
		sourceColumn: units_sold_clicks_7d

		annotation SummarizationSetBy = Automatic

	column keyword_id
		dataType: int64
		formatString: 0
		lineageTag: a63d5eeb-94b0-4571-8373-97b236c52c9b
		summarizeBy: sum
		sourceColumn: keyword_id

		annotation SummarizationSetBy = Automatic

	column attributed_sales_same_sku_7d
		dataType: double
		lineageTag: 9c3badd8-1351-4a40-969e-8265d9cc827a
		summarizeBy: sum
		sourceColumn: attributed_sales_same_sku_7d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_1d
		dataType: double
		lineageTag: c80737df-976f-465e-8d92-591f21b44e53
		summarizeBy: sum
		sourceColumn: sales_1d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ad_group_id
		dataType: int64
		formatString: 0
		lineageTag: 0c4100a9-ea49-45c6-af8d-cfbb3ffb0a4c
		summarizeBy: sum
		sourceColumn: ad_group_id

		annotation SummarizationSetBy = Automatic

	column keyword_bid
		dataType: double
		lineageTag: 04cbaceb-7e96-48be-9fc7-2fed1171f4ff
		summarizeBy: sum
		sourceColumn: keyword_bid

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column targeting
		dataType: string
		lineageTag: ed76abd6-67d9-46a0-8716-15de2173ca3c
		summarizeBy: none
		sourceColumn: targeting

		annotation SummarizationSetBy = Automatic

	column purchases_same_sku_14d
		dataType: int64
		formatString: 0
		lineageTag: 891929ca-2353-48db-a365-e952dc603897
		summarizeBy: sum
		sourceColumn: purchases_same_sku_14d

		annotation SummarizationSetBy = Automatic

	column units_sold_other_sku_7d
		dataType: int64
		formatString: 0
		lineageTag: 42ec069b-ebd6-489f-b70f-36a1865e869c
		summarizeBy: sum
		sourceColumn: units_sold_other_sku_7d

		annotation SummarizationSetBy = Automatic

	column purchases_same_sku_1d
		dataType: int64
		formatString: 0
		lineageTag: 6af9f4f6-8f47-4513-b342-9ee3591ed5bc
		summarizeBy: sum
		sourceColumn: purchases_same_sku_1d

		annotation SummarizationSetBy = Automatic

	column campaign_budget_type
		dataType: string
		lineageTag: be51f92d-f452-4bbe-8cd9-99616776d77a
		summarizeBy: none
		sourceColumn: campaign_budget_type

		annotation SummarizationSetBy = Automatic

	column ad_keyword_status
		dataType: string
		lineageTag: 0ca4a71c-173a-43f1-8024-3309eb40b995
		summarizeBy: none
		sourceColumn: ad_keyword_status

		annotation SummarizationSetBy = Automatic

	column keyword_type
		dataType: string
		lineageTag: fa5577a6-005b-43e2-b1cc-7fd674f34add
		summarizeBy: none
		sourceColumn: keyword_type

		annotation SummarizationSetBy = Automatic

	column purchases_1d
		dataType: int64
		formatString: 0
		lineageTag: cb66db42-181e-48b5-99b3-d499c097ca77
		summarizeBy: sum
		sourceColumn: purchases_1d

		annotation SummarizationSetBy = Automatic

	column units_sold_same_sku_7d
		dataType: int64
		formatString: 0
		lineageTag: 61933d0e-14d8-4fa9-b30b-927dd2519840
		summarizeBy: sum
		sourceColumn: units_sold_same_sku_7d

		annotation SummarizationSetBy = Automatic

	column cost
		dataType: double
		lineageTag: ae5dd048-0dd3-4884-8c2a-6631764fd850
		summarizeBy: sum
		sourceColumn: cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_14d
		dataType: double
		lineageTag: ff69651b-ab3b-4519-9bd0-b8434c7f68dc
		summarizeBy: sum
		sourceColumn: sales_14d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column acos_clicks_7d
		dataType: double
		lineageTag: b342e192-e415-433c-bdd8-952f932b941e
		summarizeBy: sum
		sourceColumn: acos_clicks_7d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column sales_30d
		dataType: double
		lineageTag: 4f3791f1-870b-443e-bb92-6290a464e390
		summarizeBy: sum
		sourceColumn: sales_30d

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column impressions
		dataType: int64
		formatString: 0
		lineageTag: 5c6a428f-8931-492a-9b88-65f73ae5ca82
		summarizeBy: sum
		sourceColumn: impressions

		annotation SummarizationSetBy = Automatic

	column purchases_same_sku_30d
		dataType: int64
		formatString: 0
		lineageTag: 2e973f95-2f4a-4fba-861f-26d98073bbb4
		summarizeBy: sum
		sourceColumn: purchases_same_sku_30d

		annotation SummarizationSetBy = Automatic

	column purchases_14d
		dataType: int64
		formatString: 0
		lineageTag: 77ce4302-ecf9-4bee-a38e-946d0ccc10d4
		summarizeBy: sum
		sourceColumn: purchases_14d

		annotation SummarizationSetBy = Automatic

	column purchases_30d
		dataType: int64
		formatString: 0
		lineageTag: b26cc931-1497-4950-bd84-8074c62fc121
		summarizeBy: sum
		sourceColumn: purchases_30d

		annotation SummarizationSetBy = Automatic

	column clicks
		dataType: int64
		formatString: 0
		lineageTag: 0ed50c1c-4087-43af-a3c5-12a89ff8226d
		summarizeBy: sum
		sourceColumn: clicks

		annotation SummarizationSetBy = Automatic

	column campaign_name
		dataType: string
		lineageTag: 8983eaf8-fc4a-40b6-97d8-ee2840110434
		summarizeBy: none
		sourceColumn: campaign_name

		annotation SummarizationSetBy = Automatic

	column marketplace
		dataType: string
		lineageTag: 9164fac2-3cdf-47db-8913-271ab788c700
		summarizeBy: none
		sourceColumn: marketplace

		annotation SummarizationSetBy = Automatic

	partition 'SP search_term' = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("edgepify.app", "ecommerce", [HierarchicalNavigation=true]),
				    sponsored_products = Source{[Schema="sponsored_products"]}[Data],
				    search_term1 = sponsored_products{[Name="search_term"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(search_term1,{"created_at", "updated_at", "campaign_status"}),
				    #"Lowercased Text" = Table.TransformColumns(#"Removed Columns",{{"search_term", Text.Lower, type text}})
				in
				    #"Lowercased Text"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

