table 'SQP Rankings'
	lineageTag: 1f2eafa0-2dd4-4d63-8788-a61dc369ef70

	column marketplace
		dataType: string
		lineageTag: 7838b242-c145-468f-80c4-3121d23cc363
		summarizeBy: none
		sourceColumn: marketplace

		annotation SummarizationSetBy = Automatic

	column 'top search query'
		dataType: string
		lineageTag: 388f9a49-a7d7-4047-9479-5108e1fc95d0
		summarizeBy: none
		sourceColumn: top search query

		annotation SummarizationSetBy = Automatic

	column total_purchases_brand_count
		dataType: int64
		formatString: 0
		lineageTag: 74cc777e-0da6-4947-8c6a-946f00ffa607
		summarizeBy: sum
		sourceColumn: total_purchases_brand_count

		annotation SummarizationSetBy = Automatic

	column rank
		dataType: int64
		formatString: 0
		lineageTag: caddb09d-d747-4fd8-8dc3-73275ca39466
		summarizeBy: sum
		sourceColumn: rank

		annotation SummarizationSetBy = Automatic

	partition 'SQP Rankings' = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(PostgreSQL.Database("edgepify.app", "ecommerce"), "SELECT#(lf)    marketplace,#(lf)    search_query,#(lf)    SUM(purchases_brand_count) AS total_purchases_brand_count,#(lf)    RANK() OVER (PARTITION BY marketplace ORDER BY SUM(purchases_brand_count) DESC) AS rank#(lf)FROM brand_analytics.search_query_performance_brand_view#(lf)WHERE purchases_brand_count > 0#(lf)GROUP BY marketplace, search_query#(lf)ORDER BY marketplace DESC, total_purchases_brand_count DESC", null, [EnableFolding=true]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"search_query", "top search query"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

