    CALCULATE(
        MAX('COGS (WW)'[COGS]),
        FILTER(
            'COGS (WW)',
            'COGS (WW)'[ASIN] = SELECTEDVALUE(amazon_orders_summary_view[asin]) &&
            'COGS (WW)'[Date] = SELECTEDVALUE(amazon_orders_summary_view[purchase_date]) &&
            'COGS (WW)'[Marketplace] = SELECTEDVALUE(amazon_orders_summary_view[marketplace])
        )
    )